### ISSUE TITLE
raycasts cannot find is_in_group()

### ISSUE THREAD

**Issue by Xephyrose** [godot-jolt/godot-jolt#655] opened 2023-10-23 18:51 UTC
It seems to me that if you send a raycast, check when it collides, and find the group of the node it collided with, it cannot find the group and subsequently assumes there isn't one. I've gone ahead and recreated it using godot 4.1.0 and 4.1.2 and Jolt Physics 0.8.0 and 0.9.0. Only happens when jolt is installed.

[Jolt Raycast Bug Minimal Reproduction.zip](https://github.com/godot-jolt/godot-jolt/files/13077991/Jolt.Raycast.Bug.Minimal.Reproduction.zip)

**Comment by mihe** [comment] 2023-10-23 19:55
Effectively a duplicate of #273 (or #644 if you want something more concise).

If you look closely at the output you'll notice that when you use Godot Physics it prints `HitCharacterBody3D2` (the enemy, note the `2` at the end) whereas when you use Jolt it prints `HitCharacterBody3D` (the player).

This is because your `RayCast3D` is childed to your `Camera3D` and not to your `CharacterBody3D`. This means its `exclude_parent` property won't have any effect at all and hits against the `CharacterBody3D` will be evaluated. Godot Physics and Jolt differ here in that Godot Physics only considers `ConcavePolygonShape3D` and `HeightMapShape3D` to have back-faces, whereas Jolt also considers convex shapes (like `CapsuleShape3D` in this case) to have back-faces as well. So you're effectively hitting the inside of the hollow player shape with Jolt, whereas Godot Physics will go right through it.

The fix/workaround is to either address your hierarchy issue to make `exclude_parent` actually do something, or you can also address it with collision layers/masks, or you can do the ray-cast through code where `hit_back_faces` is available to be disabled (as seen [here](https://github.com/godot-jolt/godot-jolt/issues/273#issuecomment-1630485231)). In Godot 4.2 `hit_back_faces` will be an exposed property on `RayCast3D` that can be unchecked as well, but that's not the case in Godot 4.1 unfortunately.

**Closed by mihe** 2023-10-23 19:55 UTC
Labels: duplicate, topic:runtime
