### ISSUE TITLE
On_Area3D_body_entered(body) Raycast crash as collider is null

### ISSUE THREAD

**Issue by heavyathan** [godot-jolt/godot-jolt#589] opened 2023-09-17 10:52 UTC
Casting a 3D Raycast with PhysicsRayQueryParameters3D.new(), engine gets a Collider_ID but Collider is <null>.
Checked that is a Godot Jolt issue as exchanging to GodotPhysics works fine

Godot 4.2 dev4

Atached minimal project: run, press down arrow until green Characterbody enters in Enemy Area3D-->using Jolt crashes
[TRIAL.zip](https://github.com/godot-jolt/godot-jolt/files/12642623/TRIAL.zip)
![crash](https://github.com/godot-jolt/godot-jolt/assets/100681249/101638b5-4bab-4aaf-be09-e862c4c8e7a7)

**Comment by mihe** [comment] 2023-09-17 10:59
Duplicate of #534.

**Closed by mihe** 2023-09-17 10:59 UTC
Labels: duplicate, topic:runtime
