### ISSUE TITLE
Cannot use multi-thread on i5-12600kf CPU

### ISSUE THREAD

**Issue by GodotHan** [godot-jolt/godot-jolt#978] opened 2024-09-06 14:20 UTC
In my project, I downloaded version 0.13 of Jolt.When the project is running, the engine will continuously add spherical rigid body nodes,and when the frame rate significantly decreased, I found that the CPU was not fully working.The specific screenshot is as follows. I have confirmed that multithreading has been enabled and the maximum number of threads has been set to -1
<img width="979" alt="1725632339862" src="https://github.com/user-attachments/assets/7764b48f-5c77-4700-bae9-69373231074e">

**Comment by GodotHan** [comment] 2024-09-06 14:21
In addition, I have tested multiple types of CPUs and found that the problem only occurs with i5-12500 and i5-12600kf

**Comment by GodotHan** [comment] 2024-09-06 14:21
In addition, I have tested multiple types of CPUs and found that the problem only occurs with i5-12500 and i5-12600kf

**Comment by GodotHan** [comment] 2024-09-06 14:21
In addition, I have tested multiple types of CPUs and found that the problem only occurs with i5-12500 and i5-12600kf

**Comment by GodotHan** [comment] 2024-09-06 14:21
In addition, I have tested multiple types of CPUs and found that the problem only occurs with i5-12500 and i5-12600kf

**Comment by jrouwe** [comment] 2024-09-06 14:53
There's very little info in this report to go on so this is very much speculation: Your i5-12500 has 6 P cores and 4 E cores, I can see from the screenshot that they're all active. If you create a big pile of spheres, it could be that the E cores are creating a bottleneck for the P cores (because they're slower). Try spreading out the spheres into 16 piles that don't collide with each other and see if that makes a difference (a pile for each thread, that way you're creating 16 islands that can easily be multithreaded).

Creating a single big pile of objects is a particularly bad performance test for a physics engine. This almost never happens in games and is a difficult scenario, so not something I optimize for.

**Comment by mihe** [comment] 2024-09-06 15:26
> Try spreading out the spheres into 16 piles that don't collide with each other

Alternatively I assume you could also set up the collision layer/mask in such a way that the bodies aren't allowed to collide with eachother.

Either way, judging the throughput of the physics engine based on the CPU utilization in Task Manager isn't going to be very helpful. Even if you have an incredibly barebones scene with no rendering whatsoever there are still plenty of other things happening in a Godot frame that aren't threaded, meaning you'll pretty much never saturate the CPU fully (in the interval used by Task Manager).

If you're able to provide a reproduction project that showcases some specific performance pitfall we can maybe take a look at that, but as @jrouwe pointed out there isn't a whole lot to go by here, and the theory about the E-cores being a potential problem sounds likely, so I'll go ahead and close this in the meantime.

**Closed by mihe** 2024-09-06 15:26 UTC
Labels: performance
