### ISSUE TITLE
Ragdolls crashing game and causing odd visual effects.

### ISSUE THREAD

**Issue by krumplespiff** [godot-jolt/godot-jolt#802] opened 2024-03-14 23:34 UTC
Normal Ragdoll:
![image](https://github.com/godot-jolt/godot-jolt/assets/139650253/56756b64-2dcd-4ba9-b3ed-125a52f6fb04)
Jolt Ragdoll:
![image](https://github.com/godot-jolt/godot-jolt/assets/139650253/9e9e20d9-7608-4047-aafd-26e1549eb016)
![image](https://github.com/godot-jolt/godot-jolt/assets/139650253/ebd632a3-028c-47ca-a613-b583d975b904)

When my character ragdolls using jolt physics the individual bones scatter at high speeds and then I crash with hundreds of the error listed below. On the default Godot physics this never happens. 

E 0:01:14:0710   instance_set_transform: Condition "!v.is_finite()" is true.
  <C++ Source>   servers/rendering/renderer_scene_cull.cpp:922 @ instance_set_transform()

I have observed that in the Godot physics my mesh tends to get stuck in the terrain mesh, which makes me wonder if this is also happening with Jolt, but instead of getting stuck in the mesh it has throws this error.

**Comment by mihe** [comment] 2024-03-15 01:08
That error is unfortunately pretty generic, but usually indicates that some calculation in the simulation has resulted in a NaN. The most common cause of this that I've seen is having a body or shape with a scale of 0 on one or more axes.

If you're able to provide some kind of repro project that would help narrow things down.

**Comment by mihe** [comment] 2024-03-20 10:54
Since I have no way of reproducing this specific scenario I have to assume it's related to invalid scaling of some sort. It's not unlikely that this is related to godotengine/godot#77575, where no matter what you do you end up with invalid scaling for `PhysicalBone3D`, which has been fixed in Godot 4.3.

I've now also (as of #810) added a bunch of error-handling to help catch invalid scaling before it makes its way into the simulation and eventually into the rendering server, where it inevitably causes that `Condition "!v.is_finite()" is true.` error.

Again, if you can provide me with a repro project @krumplespiff I can confirm whether this is actually the case, but until then I'll go ahead and close this.

**Closed by mihe** 2024-03-20 10:54 UTC
Labels: topic:runtime

**Comment by krumplespiff** [comment] 2024-05-21 22:52
thank you for your commentary, unfortunately I don't think I would be able to upload a repro project without sharing my whole game since the error is not definitively reproducible. Once godot 4.3 comes out I will see if that fixes it. If 4.3 doesnt help then we could do a screen share to walk through the issue.

I went in and deleted all the scale key frames on my character to ensure scaling wasn't happening but unfortunately the issue still persists.
