### ISSUE TITLE
Small bodies sink into or hover above other bodies

### ISSUE THREAD

**Issue by beiller** [godot-jolt/godot-jolt#752] opened 2024-01-17 17:15 UTC
When I try to add manual collision exceptions, it doesn't appear to have any effect.

On collision shape debug mode, the collision notifications (red triangles?) pop up all over things that I had configured to be exempt. I use the following pattern:

```
var item1: RigidBody3D = get_node("RigidBody3D")
var item2: RigidBody3D = get_node("RigidBody3D2")
item1.add_collision_exception_with(item2)
item2.add_collision_exception_with(item1)
```

Also I tried:

```
PhysicsServer3D.body_add_collision_exception(item1.get_rid(), item2.get_rid())
PhysicsServer3D.body_add_collision_exception(item2.get_rid(), item1.get_rid())
```

And it does not appear to be taking effect. One thing I do notice, is connected bodies by a joint of any type with exclude collisions seems to work fine! I am mostly sure it's not working but I am still testing and its difficult to test properly.

Edit-
Maybe an important note, the RigidBody3D has multiple collision shapes

Edit
Here is some testing. It seems to have an effect, but is it correct? Shouldn't the balls be perfectly aligned when collision is excepted?

### no collision exception
![Screenshot_2024-01-17_12-27-38](https://github.com/godot-jolt/godot-jolt/assets/6775116/e4e286e2-94d5-46cc-8556-23d74daabdcb)

### collision exception
![Screenshot_2024-01-17_12-28-09](https://github.com/godot-jolt/godot-jolt/assets/6775116/42bafda7-1c87-4c22-9a13-ff68ee12b850)

**Comment by beiller** [comment] 2024-01-17 17:36
Ya in godot physics, both the spheres are exactly on top of one another

### Exception enabled
![Screenshot_2024-01-17_12-35-13](https://github.com/godot-jolt/godot-jolt/assets/6775116/5583e07b-e11e-4ba3-a167-a7dc49cf9e6c)

### disabled
![Screenshot_2024-01-17_12-35-26](https://github.com/godot-jolt/godot-jolt/assets/6775116/40531d3b-193a-4ae8-ad3b-4b547982d5e5)

**Comment by mihe** [comment] 2024-01-17 17:41
That's odd. If you're able to zip up that project (or some other where you can repro it) and upload it here I can take a closer look at it.

You can just drop the zip file onto the comment box, much like with the images. Feel free to omit the Godot Jolt binaries if they exceed the size limit.

**Comment by beiller** [comment] 2024-01-17 18:01
[PhysicsDebug.zip](https://github.com/godot-jolt/godot-jolt/files/13966843/PhysicsDebug.zip)

Here is the project with no Jolt plugin, just Godot Physics. I saw mentioned somewhere speculative collision, could that be the cause?

[PhysicsDebug.zip](https://github.com/godot-jolt/godot-jolt/files/13966851/PhysicsDebug.zip)

**Comment by beiller** [comment] 2024-01-17 18:05
Now I'm not sure, it seems okay, but not exact. Maybe that is just a difference in implementation?

**Comment by mihe** [comment] 2024-01-17 18:28
The collision exceptions are working as intended, but yes, the default project settings don't work very well when you have collision shapes this small.

You'll note that one sphere is sinking into the ground, which is because the "Contact Allowed Penetration" setting is set to 0.02 by default, which is about 1/4th the size of your sphere. Setting that setting to something like 0.005 should make that less noticeable.

The reason why the other sphere is stopping before hitting the ground is indeed because of the speculative collisions (by the looks of it) which is also set to 0.02 by default. You can set "Contact Speculative Distance" to 0.005 as well and you'll see something that behaves more like Godot Physics.

See #374 for a similar issue.

I'm not entirely sure what other side effects (other than worse performance) you'll see when changing these settings. In general things are not typically tuned for objects this small, as mentioned in [the readme](https://github.com/godot-jolt/godot-jolt#what-else-is-different).

**Comment by mihe** [comment] 2024-01-18 12:17
I'll go ahead and close this. Let me know if changing the above mentioned settings resolves the issue for you, @beiller.

**Closed by mihe** 2024-01-18 12:17 UTC
Labels: topic:usage
