### ISSUE TITLE
Area is null when interfacing with PhysicsServer3D

### ISSUE THREAD

**Issue by jbromberg** [godot-jolt/godot-jolt#791] opened 2024-02-19 01:54 UTC
The following line works as expected when using Godot's physics engine and when using Jolt it throws an error.

```gdscript
PhysicsServer3D.area_get_param(get_world_3d().space, PhysicsServer3D.AREA_PARAM_GRAVITY)
```

The error:
```
Parameter "area" is null.
  <C++ Source>   ./src/servers/jolt_physics_server_3d.cpp:513 @ _area_get_param()
```

**Comment by mihe** [comment] 2024-02-19 10:58
Duplicate of #777. Fixed in #778.

**Closed** 2024-02-19 10:59 UTC
Labels: duplicate, topic:runtime
