### ISSUE TITLE
Incorrect gravity (space override) on a Rigid/CharacterBody3D after reparenting

### ISSUE THREAD

**Issue by tcoxon** [godot-jolt/godot-jolt#919] opened 2024-07-17 16:13 UTC
Version: 0.12.0

In my project, I use gravity-manipulating Area3D nodes to produce the appearance of RigidBody3D/CharacterBody3Ds bobbing on water. My project also pools enemies (CharacterBody3Ds) so that they can be cheaply spawned/despawned as they move in and out of LOD zones.

Since switching to Jolt I noticed that some enemies float up into the air. What happens is that an enemy is floating in water, moves out of range, gets reclaimed by the pool, then recycled to produce an enemy on land. Despite not being in water, the new enemy has gravity as if it's in water.

Minimal reproduction project: [jolt-gravity.zip](https://github.com/user-attachments/files/16269352/jolt-gravity.zip)

When you hit the space key, it detaches the body from the tree, changes its position to one outside the water, and then reattaches it to the tree. If you hit space while it's in the "water" area, it flies up off the screen. This project prints the gravity acting on the body each frame - so you can see that it still has "water" gravity after reparenting.

By changing the project settings you can see that this doesn't happen with GodotPhysics.

If you connect to the body_exited signal on the Area3D, the body_exited signal does appear to fire when the body is removed from the tree. So it's not simply that the physics server thinks the body is still overlapping the area.

**Comment by mihe** [comment] 2024-07-17 16:49
Thank you for reporting this, and for the very succinct reproduction project.

This seems to be another manifestation of the bug that was just fixed in #917, funnily enough.

> If you connect to the body_exited signal on the Area3D, the body_exited signal does appear to fire when the body is removed from the tree. So it's not simply that the physics server thinks the body is still overlapping the area.

The `Area3D` rightfully picks up on the disappearing contact, so emits the signal as you mentioned, but the `RigidBody3D` in this case unfortunately doesn't pick up on that so hangs on to the `Area3D` reference internally.

Until I can publish another release your options are basically:

1. Do something similar to the temporary workaround I mentioned [here](https://github.com/godot-jolt/godot-jolt/issues/773#issuecomment-2227391539).
2. [Build](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) from source yourself.
3. Stick with Godot Physics for now.

In your reproduction project option 1 would look like this:

```diff
func test() -> void:
+	var box_layer := box.collision_layer
+	box.collision_layer = 0
+	await get_tree().physics_frame
+	await get_tree().process_frame
	remove_child(box)
+	box.collision_layer = box_layer
	box.position = Vector3(0, 1, 0)
	box.linear_velocity = Vector3(0, 1, 0)
	add_child.call_deferred(box)
```

I'm hoping to publish another pre-release here on GitHub soon, maybe this weekend, but I'd like to get a few more things in before then, so I can't make any promises.

**Closed by mihe** 2024-07-17 16:49 UTC
Labels: needs triage
