### ISSUE TITLE
Characterbody 3d and Rigidbody 3d have some weird interaction

### ISSUE THREAD

**Issue by wolfsmith520-github** [godot-jolt/godot-jolt#1034] opened 2024-12-22 15:51 UTC
I am try to make a source engine like character contrller. And when I try to walk down a rigidbody box the box bounced me away and fly away. After I swicth back to godot physics, it works fine. 
Do I need to change some settings? I did tried it but not work.

The original project is [This Script](https://github.com/majikayogames/SimpleFPSController/blob/bc01cc86f117b2b90187e4c44249f97edf451c4f/FPSController/FPSController.gd)

Here is the version I have : https://gist.github.com/wolfsmith520-github/a21f6b3eabdfd7b3bb64fe6eaee58dcf
btw I tested the go up down stair script, the issue is not there.

Here is a video to show the problem

https://github.com/user-attachments/assets/9a8eebd6-49c9-4665-bcd6-dbde0cd55587

**Comment by mihe** [comment] 2024-12-28 13:13
Without looking at your character controller script too closely, I would guess that this is a duplicate of #761.

There are some minor discrepancies in the implementation of `PhysicsServer3D.body_test_motion`  (which powers `test_move`, `move_and_collide` and `move_and_slide`) between this extension and Godot's own physics engine that prompts this behavior to happen more often with Jolt, but it is reproducible with Godot Physics as well, as seen in the issue I linked.

See [my comment](https://github.com/godot-jolt/godot-jolt/issues/761#issuecomment-1913568126) in the issue for how to best resolve this.

**Closed** 2024-12-28 13:14 UTC
Labels: duplicate, topic:runtime
