### ISSUE TITLE
`BoxShape3D` with no margin yields erratic normals

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#536] opened 2023-08-10 05:05 UTC
Hello again,

Trying to isolate this one into an MRP took me a day and cost me my entire sanity. There is no god. I will never be the same.

I really have nothing else to say aside from changing the y position of the player in this demo to 2.165 instead of 2.164 flips the sign of the normal reported (from a floor to a ceiling). No clue why, and it causes my character controller to randomly halt on these stairs. I can't seem to recreate this when the stairs are at another y rotation. I don't know why I'm cursed to find these breaking edge cases.

Here is the MRP. 
[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12308962/bug.zip)

**Comment by mihe** [comment] 2023-08-10 08:18
Yeah, this was a weird one.

I wasn't able to reproduce it at first, since I use the MSVC compiler in my day-to-day development, but the Clang compiler when building the distributed releases, due to it generating faster code. Sure enough, this issue was only reproducible when using Clang with optimizations enabled and (more importantly) only when aggressive floating-point optimizations were enabled, i.e. when passing `-ffast-math` (or what MSVC calls `/fp:fast`) to the compiler.

I honestly can't be bothered to dig into where exactly this discrepancy is originating from, so I'll just go ahead and rip out these compiler flags. It's not the first time there's been some strange discrepancy with Clang while using this flag, and it probably wouldn't be the last, so I'll just sacrifice some percentage point of performance for accuracy/sanity.

**Comment by Gamepro5** [comment] 2023-08-13 05:00
I just encountered the same bug again with the build provided by you [here](https://github.com/godot-jolt/godot-jolt/discussions/544#discussioncomment-6710845). I had to manually print and set on _ready the position and rotation values because the editor would not let me paste them in. Here is a new MRP. I don't understand how I instantly found it again, I'm so unlucky.
[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12328839/bug.zip)

**Comment by mihe** [comment] 2023-08-13 11:47
Well, that one is reproducible regardless of the compiler, so I guess the `-ffast-math` stuff was largely a red herring that just shifted some bits around and prevented the repro from happening in that particular instance.

I trimmed your repro down a bit more and managed to get something that I could reproduce in Jolt's `Samples` application, so I went ahead and sent this upstream: jrouwe/JoltPhysics#671

**Comment by mihe** [comment] 2023-08-28 12:02
(Quote from discussion in [91726af](https://github.com/godot-jolt/godot-jolt/commit/91726af64c38bedcd28da39c96539f32bb146dd7))

> So I found more regressions than I have time to properly make an MRP for. In the meantime, to show what I mean, try moving around for 5 seconds in this https://github.com/Gamepro5/Custom_CharacterBody3D_Movement_System (no need to look at the character controller's code, it isn't relevant)
and then replace the godot jolt included with that repo (older) with this modern one. I'm going to wait for what is considered to be a stable release before slamming my head against godot to try to make an MRP. There are also some regressions with the current stable build, I suspect it has to do with 0.6.0's Fixed issue where bodies would catch on internal edges of ConcavePolygonShape3D..
> 
> What is driving me nuts is that I observe a difference in my actual game I'm making, but cannot seem to recreate the same print statements in the MRP despite having identical environments. I know its not me though because using an older version of jolt doesn't have these issues, so I'm kind of losing my mind.

I tried the project you linked and can see that there's certainly more jank when traversing the stair-like objects, including getting stuck sometimes. I can also confirm that reverting jrouwe/JoltPhysics#683 seems to undo that.

As for the regressions you mention with regards to 0.6.0-stable, that change you point out will indeed have a negative effect on your particular character controller, but that should be addressed by the proposed algorithm in jrouwe/JoltPhysics#630.

**Comment by Gamepro5** [comment] 2023-08-28 20:57
Alright, I after a lot of pain, I narrowed down one of the differences. The one where the depenetration seems to be off I can't seem to reproduce, but hopefully it's related in some way to this. I dont know if this is a regression or a fix, but they work differently and one doesn't report a collision at all. This causes what my character controller thought was a previously safe position to move around on to be "stuck inside something" and no movement can be done.

[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12458175/bug.zip)

> As for the regressions you mention with regards to 0.6.0-stable, that change you point out will indeed have a negative effect on your particular character controller, but that should be addressed by the proposed algorithm in https://github.com/jrouwe/JoltPhysics/issues/630.

I am preparing an MRP for this. Give me a little bit. I will post it here.

**Comment by Gamepro5** [comment] 2023-08-28 21:16
> I am preparing an MRP for this. Give me a little bit. I will post it here.

[bug060.zip](https://github.com/godot-jolt/godot-jolt/files/12458251/bug060.zip)

Here is the difference between 0.6.0  and a the version before that. Try running this as is, observe the normals, and then update to the stable build of godot jolt (0.6.0-stable). Run it again and observe the normals.

I am fairly confident this one is a bug, as the motion is down and so the normal of the crater's slope should not be reported.

I also don't quite understand what you changed for `Fixed issue where bodies would catch on internal edges of ConcavePolygonShape3D.`. I haven't observed this issue (https://github.com/godot-jolt/godot-jolt/issues/530) being fixed. With that patch note.

**Comment by Gamepro5** [comment] 2023-08-29 17:51
> This one seems to be a fix, actually. The master build (using https://github.com/jrouwe/JoltPhysics/pull/683) reports a collision that should rightfully be reported, whereas it doesn't with 0.6.0-stable (or even Godot Physics in this case).

The problem with this being reported as a collision is that once the shape is in that position, it cannot move at all on the x-z plane because a collision is instantly reported. This isn't an issue when the shape margins are enabled. In other words, the `move_and_collide()` puts me in a constant state of collision instead of right before a collision is about to take place. Since Godot physics doesn't behave this way either, and the update seems to make it a lot more sensitive to trimesh shapes, perhaps it's an implementation of jolt bug?

The second thing you mentioned about 0.6.0 makes sense. I guess I'll wait for the algorithm mentioned by jrouwe.

**Comment by mihe** [comment] 2023-08-29 19:28
> Since Godot physics doesn't behave this way either, and the update seems to make it a lot more sensitive to trimesh shapes, perhaps it's an implementation of jolt bug?

When taking a second look at it I now realize that `move_and_collide` was being run with the default parameters, meaning `test_only = false` and `recovery_as_collision = false`. I thought it was the opposite. That should ideally not report a collision, I guess, as the recovery should have pushed the body far enough away for the cast to not hit anything.

I'll dig into it a bit more.

**Closed** 2023-09-05 14:47 UTC
Labels: bug, topic:runtime, external, severity:minor
