### ISSUE TITLE
Collisions from recoveries are not reported by body_test_motion

### ISSUE THREAD

**Issue by DinkeyKing** [godot-jolt/godot-jolt#894] opened 2024-06-08 09:33 UTC
Unlike the 0.12.0 version, in the 0.13.0-beta1 version the collisions from recoveries are not being reported by PhysicsServer3D.body_test_motion. This can be noticed by not having the recovery collision reported for example when recovering after a floor snap in the previous physics frame, or when another body has moved onto the the character body and recovering from that collision. (The given motion is zero or not in the direction of the collision in these cases, so it's purely recovery.)  This is regardless of how large the safe margin is. Is it possible that the old behaviour can be brought back?

**Comment by mihe** [comment] 2024-06-08 09:45
By reported I take it you mean the slide collisions in `CharacterBody3D`, or are you actually using `body_test_motion` directly?

**Comment by DinkeyKing** [comment] 2024-06-08 09:50
I'm using it directly, but I've also tested it with CharacterBody3D's move_and_slide by getting the slide collisions, and it's the same in both cases.

**Comment by mihe** [comment] 2024-06-08 10:23
Would you be able to provide some kind of (preferably minimal) repro project showing your `body_test_motion` problem? I'm a bit thrown off by the fact that you mention that a zero motion vector yields the same problems. If anything, the behavior as of 0.13.0-beta1 should give you *more* recovery collisions, since there's no discarding of contacts happening whatsoever when you provide a zero motion vector, unlike before where I would purposefully always discard very shallow contacts.

**Comment by DinkeyKing** [comment] 2024-06-08 10:32
[min-repo.zip](https://github.com/user-attachments/files/15747577/min-repo.zip)
I can detect the difference in this by adding the 0.13.0-beta1 version of Godot Jolt and checking the slide collisions.

**Comment by mihe** [comment] 2024-06-08 11:00
Sorry, I should have been more clear. I was interested in seeing your issues when using `body_test_motion` directly, not `move_and_slide`.

There are indeed known issues with `move_and_slide` currently, which stem from the fact that `move_and_slide` doesn't report the collision results from its floor-snapping anywhere. This has however been an issue even before 0.13.0-beta1. In fact, when running your repro with 0.12.0-stable in Godot 4.2.2-stable I can still reproduce the issue of ending up zero slide collisions when walking around for a bit, although it's less prominent than when using 0.13.0-beta1.

This is realistically only ever going to be properly fixed on the Godot side of things, and is something I've been meaning to make a pull request for, but it's highly unlikely that any such change would make it in for Godot 4.3-stable.

**Comment by DinkeyKing** [comment] 2024-06-08 11:13
[min-repo.zip](https://github.com/user-attachments/files/15747670/min-repo.zip)
Sorry for my previous misunderstanding. I've written a minimal collision response using body_test_motion and I print out the collision count, should be reproducable with this repo.

**Comment by mihe** [comment] 2024-06-08 12:55
Ah.

You're not actually providing a zero motion vector though (for the most part), since your `apply_friction` will cause your velocity to approach zero in an asymptotic manner and only ever reach actual zero (after a while) due floating-point precision. If you change the body of your `set_initial_velocity` to just be `velocity = get_input_direction() * run_speed` you'll find that collisions are reported.

The fundamental problem here is that `recovery_as_collision` doesn't actually do what you probably think it does, nor what the official documentation states that it does. [The documentation](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html#class-physicsbody3d-method-move-and-collide) states that:

> If `recovery_as_collision` is `true`, any depenetration from the recovery phase is also reported as a collision

... which is not true for Godot Physics nor Godot Jolt. What it actually does is just force the final collision check to run regardless if the shape-casting part of `body_test_motion` hit anything or not, and then it relies on the actual recovery not having depenetrated fully, thereby resulting in a collision for the final collision check. So the collisions being reported from `recovery_as_collision` aren't the actual recovery collisions.

This causes a lot of trouble, since any implementation of `body_test_motion` is more or less forced to always undershoot the recovery in order to report collision results from `recovery_as_collision`, but that ends up causing problems like triggering false positives for the `floor_block_on_wall` mechanism in `CharacterBody3D` and other types of "ghost collisions".

Implementing `recovery_as_collision` the way that the official documentation claims it's implemented is likely to cause the same issues as when just undershooting the recovery, although I can't remember having actually tried this. It might be worth an experiment just to see what happens.

The only other alternative would be to introduce a project setting to disable the new contact discarding that was introduced in #860. That might perhaps fix things for your particular custom character controller, but disabling that discarding would completely break the regular `move_and_slide`. I'd rather not go back to the behavior in 0.12.0-stable either, since that was broken in other ways.

**Comment by DinkeyKing** [comment] 2024-06-08 13:20
Thanks for clarifying. I really thought that `recovery_as_collision` means that the intersections before the recovery are reported as collisions, which it only seemed to work that way. Even if I do an extra collision check before doing the motion, my problem is that the other methods provided for shape intersection checks do not give out all the information of the collisions. `get_rest_info` only returns info about one collision, `intersect_shape` only returns info about the colliders, and nothing else about the collision, `collide_shape` returns the intersection points, but no information which colliders those points belong to, so I'm stumped on how to get the collisions the character body recovered from.

**Comment by DinkeyKing** [comment] 2024-06-08 13:55
Oh wait, I can just call `body_test_motion` with zero motion before moving the character, and get all the data of the current intersections that way, which seems to work. Neat.

**Comment by mihe** [comment] 2024-06-08 14:13
> Even if I do an extra collision check before doing the motion, my problem is that the other methods provided for shape intersection checks do not give out all the information of the collisions.

Yeah, the state of shape queries in Godot is somewhat unfortunate at the moment. It's also something I've been meaning to make pull requests for, but it's not a trivial change.

> I can just call `body_test_motion` with zero motion before moving the character, and get all the data of the current intersections that way, which seems to work.

Running `body_test_motion` an extra time with zero motion would indeed probably be the best compromise.

> It's one extra collision check though.

It's a lot more than one collision, unfortunately. The recovery part is up to 4 collision checks. The cast part (even with zero motion) is at least another 4 collision checks, and then the final collision check is another one. So 9 collision checks in total.

Anyway, I'll go ahead and close this for now. There's not a whole lot I can reasonably do to "fix" this.

**Closed by mihe** 2024-06-08 14:13 UTC
Labels: wontfix, topic:runtime
