### ISSUE TITLE
Using `Enhanced Internal Edge Removal` causes some thin objects to clip through surfaces

### ISSUE THREAD

**Issue by MajorMcDoom** [godot-jolt/godot-jolt#945] opened 2024-08-18 19:08 UTC
Leaving `Enhanced Internal Edge Removal` on causes some thin objects to clip through surfaces where they otherwise do not if the feature is disabled.

![HammerCollider](https://github.com/user-attachments/assets/df65612e-de66-4c12-92c2-22cb9c7953d8)
![HammerComparison](https://github.com/user-attachments/assets/c15b0594-1960-4391-bef0-e57d2cb3e1fa)

This particular case is odd because neither the hammer nor the crate have any what I would consider "internal edges".

**Comment by mihe** [comment] 2024-08-18 19:59
Interesting. Would you be able to share a minimal repro of that by any chance, even if it's just the collision shapes of those two objects?

**Comment by MajorMcDoom** [comment] 2024-08-18 21:11
> Interesting. Would you be able to share a minimal repro of that by any chance, even if it's just the collision shapes of those two objects?

[jolt-glitch-test.zip](https://github.com/user-attachments/files/16652101/jolt-glitch-test.zip)

Sure thing, here you go. I couldn't include Jolt because it was too big, but I'm using the latest one that you just released for `4.3`.

**Comment by mihe** [comment] 2024-08-18 22:03
Hm, yeah, as you say, the enabling of that setting does seem to force the issue, and vice versa.

The size of this hammer is admittedly quite small, with the handle being a mere 3.2 cm wide and 4.5 cm deep, which is known to cause a number of issues, but obviously it works somewhat well when the setting is disabled.

Tinkering with the usual suspects (`contact_speculative_distance` et al) doesn't really seem to get me anywhere either.

Would you mind taking a look at this one, @jrouwe? More specifically the `hammer_test.tscn` scene. I was also able to repro it in `Samples` using a snapshot as well: [jolt_snapshot_2024-08-18_23-58-55_172.zip](https://github.com/user-attachments/files/16652424/jolt_snapshot_2024-08-18_23-58-55_172.zip)

**Comment by MajorMcDoom** [comment] 2024-08-18 23:10
> Hm, yeah, as you say, the enabling of that setting does seem to force the issue, and vice versa.
> 
> The size of this hammer is admittedly quite small, with the handle being a mere 3.2 cm wide and 4.5 cm deep, which is known to cause a number of issues, but obviously it works somewhat well when the setting is disabled.
> 
> Tinkering with the usual suspects (`contact_speculative_distance` et al) doesn't really seem to get me anywhere either.
> 
> Would you mind taking a look at this one, @jrouwe? More specifically the `hammer_test.tscn` scene. I was also able to repro it in `Samples` using a snapshot as well: [jolt_snapshot_2024-08-18_23-58-55_172.zip](https://github.com/user-attachments/files/16652424/jolt_snapshot_2024-08-18_23-58-55_172.zip)

Just for more info:
In the repro project I sent you, I tried to keep things everything on default settings. But in my own project, I have tried different values for separation, penetration, continuous collision detection, etc. None of that helped.

**Comment by jrouwe** [comment] 2024-08-19 19:58
FYI I can reproduce the issue, but I have no idea what's causing it. The collision shapes look good (albeit a bit small). This is going to require some serious debugging (and time).

**Comment by jrouwe** [comment] 2024-08-19 21:09
I have a tentative fix that needs a bit more testing (see above).

**Comment by mihe** [comment] 2024-08-19 21:37
From just some crude manual testing your change seems to be working nicely in that particular scene at least. I can't seem to force any sort of clipping no matter how I throw around that hammer.

**Comment by jrouwe** [comment] 2024-08-20 19:51
Testing is complete and code has been merged. I fully understand the issue now and created a simple repro that resulted in a broken sim before and is fixed now:

![image](https://github.com/user-attachments/assets/87eaac38-5438-4374-ba76-2bd9d280cc00)

**Closed** 2024-08-20 21:44 UTC
Labels: bug, topic:runtime, external, severity:minor

**Comment by mihe** [comment] 2024-08-20 21:49
@jrouwe Is this problem specific to these types of thin sub-shapes, or is it a more general problem than that? I'm not sure how much of a hurry I should be in to cut another release.

**Comment by jrouwe** [comment] 2024-08-21 05:17
It will happen on any compound shape that forms a non-convex shape where one sub shape rests on a face and another on an edge of that face. So it could be quite common, but it is quite a specific situation.

**Comment by mihe** [comment] 2024-08-21 09:09
I'll try to cut a new release this weekend then.

**Comment by jrouwe** [comment] 2024-08-21 16:44
Maybe we should try to get the face_index fo ray casts in as well (not sure if I can make that before the weekend)

**Comment by mihe** [comment] 2024-08-21 17:30
I don't think there's any real rush with that one, necessarily, but I'm down to implement my part of it whenever. It shouldn't be that much code on the extension side of things.

**Comment by mihe** [comment] 2024-11-03 18:27
The fix for this can now be found in the newly released [0.14.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable).

Note that the release on Godot Asset Library is still pending approval, so you might need to download it from GitHub for the time being.
