### ISSUE TITLE
intersect_ray exclude Array doesnt work with RIDs

### ISSUE THREAD

**Issue by Griiimon** [godot-jolt/godot-jolt#592] opened 2023-09-18 12:04 UTC
This was reported on Discord and I haven't verified it myself:

The exclusion of objects in `PhysicsRayQueryParameters3D.intersect_ray` via `Array[RID] exclude` wasn't working after switching to Godot Jolt. Passing the object directly instead of the RID seemed to fix it.

**Comment by mihe** [comment] 2023-09-18 12:29
I'm not able to reproduce this. I can pass either the RID or the object itself just fine to `PhysicsRayQueryParameters3D.exclude`.

It's not really something I can mess up in the first place (I hope), since exclusions aren't passed directly to extensions (for complicated reasons) but instead extensions have to ask Godot if a `CollisionObject3D` is excluded from a physics query or not, which is always done using the object's RID.

If you're able to provide a repro I can take a look, but until then I'll close this as "can't repro".

**Closed by mihe** 2023-09-18 12:29 UTC
Labels: needs triage
