### ISSUE TITLE
`move_and_collide` against triangle intersection yields odd normals

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#530] opened 2023-08-03 01:36 UTC
This may seem minor, but these errors add up. I was only able to discover them by walking around with my character controller. I managed to isolate the issue in an MRP. I'm sorry I dont have much else to say, No I am not technical with collision detection, I simply rely on getting 100% correct collision normals so my [custom character physics](https://github.com/Gamepro5/Custom_CharacterBody3D_Movement_System/blob/main/player/CharactedController.gd) can work.

MRP:
[addons.zip](https://github.com/godot-jolt/godot-jolt/files/12245895/addons.zip)

**Comment by mihe** [comment] 2023-08-03 10:01
Thank you for taking the time to create the MRP, and for reporting the issue. That is not the result I would expect either.

It seems like it's related to that triangle intersection on the wall that your box is right up against, in combination with moving towards it.

I reduced your mesh down to just the relevant section of the wall and changed the motion vector to `(-0.005, 0, 0)`, and here's what the normals look like with Godot Physics:

![Godot](https://github.com/godot-jolt/godot-jolt/assets/4884246/acac2442-2233-42ab-aab1-4417699a8814)

... and here's what they look like with Godot Jolt:

![Jolt_OnlyActiveEdges](https://github.com/godot-jolt/godot-jolt/assets/4884246/17957e50-22f7-47b8-9796-c4f97052e36f)

After some tinkering with the code that powers `move_and_collide`, it seems like changing this line:

https://github.com/godot-jolt/godot-jolt/blob/976abb25f61c49573fb537984e7943eea63a1427/src/spaces/jolt_physics_direct_space_state_3d.cpp#L890

... to use `EActiveEdgeMode::CollideWithAll` instead of `EActiveEdgeMode::CollideOnlyWithActive` affects the outcome in a seemingly positive way, where it starts to look like this instead:

![Jolt_AllEdges](https://github.com/godot-jolt/godot-jolt/assets/4884246/33a87605-6c2d-4025-ac2e-2dcf5ab3b3d6)

... but the documentation for this `mActiveEdgeMode` parameter hints at `EActiveEdgeMode::CollideWithAll` potentially resulting in more "ghost collisions" though, which would be a bummer. I'll have to do some more digging to see what's going on, and maybe send this upstream if I can't figure it out.

I'm not sure if there's any good workaround in the meantime. I did manage to get rid of the problem in this particular instance by just running your mesh through Blender's "Limited Dissolve" tool, which removes a lot of the redundant triangles and thereby also that triangle intersection in the middle there, but the problem might very well show up somewhere else instead though.

**Comment by Gamepro5** [comment] 2023-08-03 22:20
Thank you so much man, every time you make me awe at how impressively you can diagnose problems and provide us with a essay level analysis. I wish you luck in finding the a good workaround :)

**Comment by Gamepro5** [comment] 2023-08-03 22:25
I have a few other bugs with my character controlled that I suspect may be a collision detection edge case. I'm going to try to also isolate them into MRPs and report them if I am able.

**Comment by Gamepro5** [comment] 2023-08-15 10:10
I think I found another example of this bug, but I don't know if it's 100% the same bug. This one affects floor collision normals. Here's an MRP:
[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12343135/bug.zip)
Do you think this issue could be a Jolt issue and not an issue with your implementation of it in Godot? If so, it might be worth sending it upstream.

**Comment by Gamepro5** [comment] 2023-08-16 18:25
I have. The problem with it is that, in the example you demonstrated, if a player is on peak of a slope, that is where the two opposite slopes suddenly change, the raycast won't correctly return that as Vector3.UP. Another problem is that, since the raycast comes from the center of the shape, if you are colliding with the edge as demonstrated by my MRP, the raycast will actually collide with the wall part of then shape. I can't really see how I could make this raycast from the collision point reported by the move and collide, because I require two points to deduce a direction. Maybe for the floor check part of the code, the direction of the vector would just be Vector3(0,-1,0).

What I'm understanding is that the problem is solved by jolt, but GDNative doesn't allow you to expose that data? I know that @rburing made the "expose the physics server through gdnative" initiative, so maybe he could add a way to expose that info?

**Comment by mihe** [comment] 2023-08-16 19:39
> The problem with it is that, in the example you demonstrated, if a player is on peak of a slope, that is where the two opposite slopes suddenly change, the raycast won't correctly return that as Vector3.UP.

If that's the result you need from that particular scenario, then exposing the surface normal somehow won't make much of a difference unfortunately, since it'll be the same result as what a ray-cast would give you, meaning the face normal of either side of the slope.

Seeing as how you're using a box shape, and you need the normal to always be aligned with the axes of the box, maybe it's possible to instead calculate such a normal from the collision points? You could (for each point) transform the point into local-space, compare the absolute X/Y/Z components and use the one with the highest value as the axis for the normal? There might be a more clever way to do it, but I feel like that should work.

**Comment by Gamepro5** [comment] 2023-08-16 20:45
> The fact remains that the collision normal isn't the surface normal, so I'm torn on whether this can even be considered an issue. Even if EActiveEdgeMode::CollideWithAll seemingly fixed this particular issue, it opens up for collisions that ideally should never happen, and will probably lead to more jank for things like move_and_slide.

Even if collision normals ≠ surface normal, I don't understand how the normals make sense.

The issue isn't really an issue if I only check for 1 collision, but the reason why I check for more than 1 is to properly handle situations where the player is moving into a corner composed of walls and ceilings. The reason why I brought up actual surface normals was because they were almost never correct when on the edge of a rectangular sloped shape using a cylinder collider. I've moved back to using a rotation locked rect because I can't really have the best of both worlds (eg having a cylinder collider report vector3.up when on the tip of a slope, and correctly returning the surface normal in https://github.com/godot-jolt/godot-jolt/issues/471 ).

> Seeing as how you're using a box shape, and you need the normal to always be aligned with the axes of the box (if I understand you correctly), maybe it's possible to instead calculate such a normal from the collision points? You could (for each point) transform the point into local-space, compare the absolute X/Y/Z components and use the one with the highest value as the axis for the normal. There might be a more clever way to do it, but I feel like that should work.

> EDIT: I guess just projecting the points (using a dot-product) onto the box shape's world-space axes is simpler than the whole local-space shenanigans.

I was describing how generating a raycast requires a start point, (in the case of your demo, this is the center of the player hull), and a target. The target would be the collision point. These two points form a direction, and that direction intersects with the wrong face in your demo. I figured that, I could perhaps instead have the raycast start at the collision point and point in the direction of the velocity. I haven't tested this though and don't know if it would work. Either way, I think that for this specific issue of BoxShape3D vs ConcavePolygonShape3D, raycasts shouldn't be necessary.

**Comment by mihe** [comment] 2023-08-16 22:47
> I don't understand how the normals make sense.

I'm running up against the limits of what I'm able to explain without potentially misrepresenting things, but from what I understand the active edge detection will override the collision normal when you collide with an edge that's shared between two triangles that are angled within a certain threshold (50 degrees in this case). Instead of using the regular collision normal it will instead use the triangle normal, which is supposed to prevent "bumping up against" triangle edges as your body approaches it, as seen in #508.

Anyway, maybe the best course of action for this particular issue is to just add a setting for this "active edge mode" for kinematic collisions specifically. I've gone ahead and created a bespoke build [here](https://github.com/godot-jolt/godot-jolt/actions/runs/5884236919) that contains a new setting under "Kinematics" called "Use Edge Detection". If you disable that setting you will switch over to `EActiveEdgeMode::CollideWithAll` and hopefully get the normals you expect.

Try that one out and let me know how it works out for you. I'm mostly curious if you notice any new problems with regards to colliding with triangle edges. If that ends up working for you then I can see about adding it for the next release.

**Comment by Gamepro5** [comment] 2023-08-16 22:50
Alright, thank you. I'll give this a shot and do extensive testing to see if there are any regressions. If I can't find any, I'll let you know and maybe it could be default. #508 does seem to be identical to this issue from a glance.

**Comment by Gamepro5** [comment] 2023-08-16 23:54
Hi mihe, I've found a regression:
[regression.zip](https://github.com/godot-jolt/godot-jolt/files/12364233/regression.zip)

I've been testing for an hour. It seems like aside from this, the collisions are much more reliable. I've been testing both on the map this issue was made on and a massive ConcavePolygonShape3D generated from a photoscanned model of a tree. I have not been able to find any issues there either. It seems like `EActiveEdgeMode::CollideWithAll` just struggles a bit with CSG geometry. I'm going to keep testing to see if I can find some more odd behavior aside from the CSG stuff.

Cheers!

**Comment by Gamepro5** [comment] 2023-08-17 01:37
[didntfixthis.zip](https://github.com/godot-jolt/godot-jolt/files/12364577/didntfixthis.zip)

I noticed that the `EActiveEdgeMode::CollideWithAll` did not seem to fix this situation, however. It improved a lot of things but not this one. It's not a regression because it didn't change it.

**Comment by mihe** [comment] 2023-08-17 10:58
I've been testing out `EActiveEdgeMode::CollideWithAll` with the default `CharacterBody3D` template (i.e. `move_and_slide`) and walking across a varied `HeightMapShape3D` terrain, and honestly it's a noticeable decrease in the amount of jank you run into. I guess it makes some kind of sense that `move_and_slide` might get thrown off by these normals as well somehow.

What I find really strange is that when running with `EActiveEdgeMode::CollideWithAll` I don't see any regression in #524, which was greatly improved by adjusting the active edge threshold from 5 to 50 degrees. But maybe the active edge detection was the actual problem there to begin with.

Maybe I should just ditch the setting and make `EActiveEdgeMode::CollideWithAll` the default behavior for all shape queries instead.

**Comment by mihe** [comment] 2023-08-17 14:06
Hm, I am however seeing quite a lot of regressions when walking around the level provided in #529, where it's now more or less impossible to walk up a `ConcavePolygonShape3D` slope greater than ~36 degrees, when using a `floor_max_angle` of 45 degrees and the default `safe_margin`, due to catching on the various triangle edges that are criss-crossing the slopes.

Just to see what would happen, I decided to switch out the normals reported by `body_test_motion` (i.e. `move_and_*`) to be surface normals instead of the collision normals, and that actually (perhaps unsurprisingly) fixed most of the issues with #529, even the ones present before this edge mode change. However, when trying out the terrain from my previous reply, I found myself seeing the same type of jank when going over a sharp bump/crest as I was seeing before this edge mode change, presumably because the normal doesn't end up smoothly transitioning across but instead snapping from one face to the other. which I guess is similar to what ends up happening with `EActiveEdgeMode::CollideOnlyWithActive`.

Anyway, clearly I was a bit quick on the trigger with that PR. I realize you're not using `move_and_slide`, so maybe there's some justification for adding the setting still, but I need to do some more in-depth debugging here to get a better sense of what the actual problem is and maybe then I can see a more holistic solution to this.

**Comment by Gamepro5** [comment] 2023-08-17 17:58
> I need to do some more in-depth debugging here to get a better sense of what the actual problem is and maybe then I can see a more holistic solution to this.

Epic. Do you have any ideas as to why this setting doesn't like CSG?

Also, yes I'm not using move_and_slide(). I'm using a bunch of move_and_collides(), so when I encounter an issue I simplify it down to a move and collide. In my mind, that should be more helpful than sending an entire character controller.

**Comment by mihe** [comment] 2023-08-17 21:27
> Do you have any ideas as to why this setting doesn't like CSG?

`CSGShape3D` is just a regular `ConcavePolygonShape3D` under the hood, so there shouldn't be anything special about them really. I guess the way the shape is triangulated can affect things or something.

> In my mind, that should be more helpful than sending an entire character controller.

Yes, that's very much appreciated, thank you.

**Comment by Gamepro5** [comment] 2023-08-17 23:24
Come to think of it, from my testing it seemed like the only thing the collide with all didn't like was perfectly flat surfaces that have streaks like so. I didn't have any issues on this tree. I find it odd that that [this ](https://github.com/godot-jolt/godot-jolt/issues/530#issuecomment-1681479488)wasn't fixed by `EActiveEdgeMode::CollideWithAll` though.

![image](https://github.com/godot-jolt/godot-jolt/assets/23440295/c5d9e77e-98cb-49cb-991b-85777ec5c3fd)

**Comment by mihe** [comment] 2023-08-23 20:02
For a moment there I figured that this setting could serve as a Good Enough™ solution to the original issue here, so I merged it and closed this, but honestly I'm not super happy about introducing this setting, for a number of reasons:

1. It makes some of the MRPs worse, like [this one](https://github.com/godot-jolt/godot-jolt/issues/530#issuecomment-1678708110), and in general will likely just lead to other (actual) edge collisions, so you're just trading one set of "incorrect" normals for another one.
2. It makes `move_and_collide` (and `test_move`) inconsistent in behavior with other shape queries like `get_rest_info`, as well as with any contacts reported by `RigidBody3D`.
3. `move_and_slide` seems to benefit greatly from using Jolt's edge detection, even with a box-shaped character, so I'm questioning the premise of disabling it in the first place.

... so I've removed/reverted the setting for now.

I've also done a bit of a deeper dive on the various MRPs here, but I want to collect my thoughts a bit before sharing them. [This](https://github.com/godot-jolt/godot-jolt/issues/530#issuecomment-1681410669) CSG one does not seem to be related to the edge detection though, and I suspect [this](https://github.com/godot-jolt/godot-jolt/issues/530#issuecomment-1681479488) one isn't either, but I have yet to confirm that one. [This](https://github.com/godot-jolt/godot-jolt/issues/530#issuecomment-1681410669) one is related, but as mentioned isn't solved by the proposed setting, and would require a different type of setting, further muddling up this whole thing.

**Comment by Gamepro5** [comment] 2023-08-23 21:22
`move_and_slide()` is a lot more complex than a single `move_and_collide()` call. I know that it uses a lot of `move_and_collide()`s inside to make it work, so maybe the reason it works fine with it is because they worked around this issue in some way instead of fixing the root problem. I'm not sure though.

**Comment by mihe** [comment] 2023-09-04 21:10
Well, it was a long and windy road to get here, but I'm closing this as `wontfix`. See jrouwe/JoltPhysics#630 for the full story.

**Closed by mihe** 2023-09-04 21:10 UTC
Labels: wontfix, topic:runtime

**Comment by mihe** [comment] 2024-02-12 13:57
There might still be a few cases that aren't covered by this new "Enhanced Internal Edge Removal" project setting, but I believe the majority of issues reported here should be resolved now, or at least greatly alleviated, so I've closed this as such.

What this new setting won't do anything about are edges inbetween disparate bodies.
