### ISSUE TITLE
Condition "slot >= slot_max" Error

### ISSUE THREAD

**Issue by Red3Tango** [godot-jolt/godot-jolt#574] opened 2023-09-03 07:13 UTC
Godot: 4.2-Dev4
Godot-Jolt: 0.7.0

Getting the following error when RayCast3D is colliding, and attempt to grab `get_collider()`.
```
E 0:00:01:0715   main.gd:17 @ _process(): Condition "slot >= slot_max" is true. Returning: nullptr
  <C++ Source>   ./core/object/object.h:1002 @ get_instance()
  <Stack Trace>  main.gd:17 @ _process()
```
Godot source code error
```cpp
ERR_FAIL_COND_V(slot >= slot_max, nullptr); // This should never happen unless RID is corrupted.
```
There is no error with Godot 4.2-Dev2 / Godot-Jolt 0.7.0, also no error when using GodotPhysics3D.

**Comment by mihe** [comment] 2023-09-03 10:41
Duplicate of #534.

**Closed by mihe** 2023-09-03 10:41 UTC
Labels: topic:runtime
