### ISSUE TITLE
Shape-casting with cylinders and rectangular shapes report incorrect normals

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#450] opened 2023-06-15 23:52 UTC
Take this code:
```
func trace_standard(origin : Vector3, dest : Vector3, shape : Shape3D, e, mask):
	var params : PhysicsShapeQueryParameters3D
	var space_state
	var results
	
	# Create collision parameters
	params = PhysicsShapeQueryParameters3D.new()
	params.set_shape(shape)
	params.transform.origin = origin
	params.set_collide_with_bodies(true)
	params.set_exclude([e])
	params.set_motion(dest - origin)
	params.set_margin(0.04)
	params.set_collision_mask(mask)
	
	hit = false
	
	# Get distance fraction and position of first collision
	space_state = get_world_3d().direct_space_state
	results = space_state.cast_motion(params)
	
	if !results.is_empty():
		fraction = results[0]
		endpos = origin + (dest - origin).normalized() * (origin.distance_to(dest) * fraction)
	else:
		fraction = 1
		endpos = dest
		return # didn't hit anything
	
	hit = true
	
	# Set next parameter position to endpos
	params.transform.origin = endpos
	
	# Get collision normal
	results = space_state.get_rest_info(params)
	if !results.is_empty():
		normal = results.get("normal")
	else:
		normal = Vector3.UP
	print(results)
```
I use this to do [quake-style stair stepping](https://thelowrooms.com/articledir/programming_stepclimbing.php). `results` is always `{   }`, leading me to believe that for Cylinder Collision Shapes, the PhysicsShapeQueryParameters3D doesn't work properly.

I am using the latest version of Jolt and Godot 4.0.2 stable.

**Comment by Gamepro5** [comment] 2023-06-16 01:08
[mrp.zip](https://github.com/godot-jolt/godot-jolt/files/11764604/mrp.zip)
Sorry for the wait, it takes a while to make a MRP. Here it is. Godot Jolt isn't included for size reasons. Simply enable it and walk forward by pressing W.

**Comment by mihe** [comment] 2023-06-16 08:23
I'm not exactly sure what I'm looking for here. Pressing W seems to walk forward as expected, and I seem to be able to walk where I'd expect to be able to walk.

I appreciate the effort in trying to reduce your project down to a repro, but an MRP typically means reducing the code down to a couple of lines that isolates the actual problem. It doesn't necessarily have to mimic the use-case in your project.

**Comment by Gamepro5** [comment] 2023-06-16 09:23
So there are walls that encircle the entire map. Walking into these walls triggers the stair stepping algorithm, which only happens because the `results`, and by extension, the `normal` are not defined. Hence the printing of `{   }` in the console, demonstrating that the PhysicsShapeQueryParameters3D isn't working as it does with Godot Physics.

If you like, I can make a quick video showing the issue.

**Comment by mihe** [comment] 2023-06-16 10:06
Right, yeah, I can see the discrepancy you're describing. That part might warrant some investigation.

If we disregard the discrepancy, is there any particular reason why you're using the safe proportion (`results[0]`) instead of the unsafe proportion (`results[1]`)?

As mentioned in Godot's [documentation](https://docs.godotengine.org/en/latest/classes/class_physicsdirectspacestate3d.html#class-physicsdirectspacestate3d-method-cast-motion):

> The safe proportion is the maximum fraction of the motion that can be made without a collision. The unsafe proportion is the minimum fraction of the distance that must be moved for a collision.

So if you're planning to call `get_rest_info` with the same parameters, albeit moved along the cast direction by some proportion, then you should ideally be using the unsafe proportion. Changing that seems to resolve that particular issue as far as I can tell.

**Comment by Gamepro5** [comment] 2023-06-16 10:23
I'm not 100% sure why the code for Trace uses only the safe portion. If changing it fixes it for now, I'll do it. I just made this issue because the behavior is very different than Godot Physics. Aside from this though, your port of Jolt has been a godsend, fixed so many problems I had with collision detection from Godot Physics. Thank you for your hard work!

**Comment by mihe** [comment] 2023-06-16 11:18
> it only fixes the issue because it fails to properly detect the stairs for stair stepping on real stairs

I'm not sure I understand what this means.

Again, there's a lot going on in this project, and any number of things could be off here. Godot Physics is not without its own bugs, which you seem aware of already, so a discrepancy isn't necessarily an issue.

If you see something that you feel rightfully should work differently in Godot Jolt, then I'd really appreciate it if you could boil it down even further, to a project with a single `cast_motion` between two shapes or something.

With that said, just as a random thought that might be completely irrelevant to your problem, it's worth keeping in mind that `cast_motion` in Godot (and Godot Jolt) explicitly ignores any initial overlaps, so if your shape overlaps with a body at the start then that entire body will be ignored by the shape-cast. That tripped me up when I first used `cast_motion`. You can do an initial `collide_shape` or `get_rest_info` to check for that. There's also methods like [`PhysicsBody3D.test_move`](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html#class-physicsbody3d-method-test-move), which does not ignore initial overlaps, but it's got [other issues](https://github.com/godot-jolt/godot-jolt/issues/337) right now that won't be resolved until Godot 4.1 is out.

> Thank you for your hard work!

I'm glad you find it useful, thank you!

**Comment by Gamepro5** [comment] 2023-06-16 19:01
You are right. It's possible that the discrepancy could be due to the person who wrote the Trace library relying on a Godot physics behavior that was not intentional. I'll try to work around it using jolt.

**Comment by mihe** [comment] 2023-06-16 19:22
I'll go ahead and close this for now. If there's something more actionable, preferably with a more minimal repro, then I'd be happy to look into it further. I hope that's alright.

**Comment by Gamepro5** [comment] 2023-06-16 20:59
I think I figured out why I was having issues with results[1]. It's not that it's incorrect, it's that normals in general aren't being properly reported with Jolt.

In this image, take a look at the floor_normal and take a look at the floor angle (created from `rad_to_deg(floor_collision_normal.angle_to(Vector3.UP))`)
![image](https://github.com/godot-jolt/godot-jolt/assets/23440295/ab0d7c31-e77f-437d-8f1b-d98bd5b64331)
As you can see the normal isn't Vector3(0,1,0) as it should be.

This is a pretty big issue. On shapes that have flat faces, it seems like the normal calculation is incorrect. The normal of the floor here (obtained by moving in the Vector3.DOWN direction) reports that it is almost 60 degrees, when in reality it is 0. Above was the behavior in Jolt, and now here is the behavior in Godot Physics:
![image](https://github.com/godot-jolt/godot-jolt/assets/23440295/b35a3092-25ef-4baa-a5f6-e2166bb259f1)
It seems like jolt calculates normals from the center of the actual shape, because changing the height of these shapes changes the normal angle. I think this is a separate issue (the root cause of why why I said "From my testing with results[1] though, it only fixes the issue because it fails to properly detect the stairs for stair stepping on real stairs. So it's technically fixed because it always makes it fail.") so let me know if you would like me to open a separate github issue.

So, to recap since I'm not sure why I'm so bad at communicating with humans right now:

1. This issue is indeed valid, the behavior for results[0] is not the same as godot physics.
2. When using your workaround, I discovered a pretty big bug with how Jolt calculates normals in general. This is unrelated to the PhysicsShapeQueryParameters3D, as this also happens with a simple `move_and_collide(Vector3.DOWN, true)`
3. This normal detection bug applies to both rectangular shapes and cylinders. Anything that is colliding with something using a flat face behaves how a capsule would calculate normals, from what I can tell.
4. This is an issue because my application of the PhysicsShapeQueryParameters3D was stair stepping. Essentially, when moving and a wall collision is detected, I do a trace up, then a trace forward, and then a trace downwards. The normal reported by the trace downwards allows me to conclude if the stair step has an angle that is less than or equal to my maximum slope angle. If it is, teleport to where the trace is.
![image](https://github.com/godot-jolt/godot-jolt/assets/23440295/1639cb74-5918-40ea-b1c7-0a5ca6e892a1)
In this graphic, even the shape with the flat base behaves similarly to the capsule. More info can be found about why this is not good [here](https://thelowrooms.com/articledir/programming_stepclimbing.php), although understanding why this behavior is required and expected isn't really important to proving the issue exists.

I really hope I was clear enough this time, I deeply apologize, I don't know what's up with me right now, I can't seem to write coherently these days. Hopefully this is better :)

**Comment by Gamepro5** [comment] 2023-06-16 22:03
It's not just shape casting, though. it's also move_and_collide(). Although I assume maybe move_and_collide() uses shape casting under the hood anyway, but even if that's so, it also applies to rectangular shapes.

**Comment by mihe** [comment] 2023-06-16 22:35
Alright, let's try this again. :)

> It's not just shape casting, though. it's also move_and_collide(). Although I assume maybe move_and_collide() uses shape casting under the hood anyway, but even if that's so, it also applies to rectangular shapes.

Yes, sorry, you're right. I was trying to rephrase the original issue in some way.

Yes, `move_and_collide` does a lot of things on the Godot side of things, but on my side of things it really only makes use of `PhysicsServer3D.body_test_motion`, which is essentially a `cast_motion` with a couple of other collision checks.

> This normal detection bug applies to both rectangular shapes and cylinders. Anything that is colliding with something using a flat face behaves how a capsule would calculate normals, from what I can tell.

Considering you note this behavior for both cylinders and boxes I suspect the issue will likely have something to do with what Godot calls "shape margins", or what Jolt and other physics engines refer to as a "convex radius", which (as I understand it) is used as part of an optimization in the type of GJK-based collision detection that Jolt uses.

Shape margins effectively "rounds off" any sharp corner that you'll find in any of the convex shapes, such as boxes, cylinders and convex hulls/polygons.

To steal an illustration from Jolt's documentation:

![Illustration of convex radius](https://jrouwe.github.io/JoltPhysics/ConvexRadius.jpg)

> In this example a box (green) was created with a fairly large convex radius. The shape is shrunken first (dashed green line) and then inflated again equally on all sides. The resulting shape as seen by the collision detection system is shown in blue. A larger convex radius results in better performance but a less accurate simulation. A convex radius of 0 is allowed.

So a cylinder ends up looking a little bit like a capsule after going through this shrinking/inflation process, and will presumably report normals accordingly.

As noted at the end there, you are allowed to use a convex radius (shape margin) of 0, which in my tests seems to get rid of any weird normals. You set this through the `margin` property on any shape, and is by default set to 0.04 by Godot, which unfortunately is not a default value I have any control over.

Note that this is not the same thing as the margin you set on `PhysicsShapeQueryParameters3D`, which is more of an extra padding around the cast shape and don't seem to affect the normals as far as I can tell.

> This issue is indeed valid, the behavior for results[0] is not the same as godot physics.

I've made a note of the discrepancy, but again, you should be using `results[1]` when passing a `cast_motion` result on to `get_rest_info`. The safe fraction/proportion represents the distance the shape can travel without hitting anything, so unless your shape is intersecting with something from the start you are more or less guaranteed to not get a hit from `get_rest_info`. Clearly Godot seems to disagree though, but seeing as how cylinders are a bit of a special case in Godot's collision detection I suspect there's something else going on there.

> I really hope I was clear enough this time, I deeply apologize, I don't know what's up with me right now, I can't seem to write coherently these days. Hopefully this is better :)

No need to apologize. It's all just ones and zeroes at the end of the day. :)

**Comment by mihe** [comment] 2023-06-16 22:43
And in case you're wondering: Godot Physics uses a different type of collision detection and as such completely ignores the shape margin property, which is why you're not seeing any weird normals there. The shape margin property is a holdover from the Bullet integration in Godot 3, which also uses GJK, as I understand it.

**Comment by Gamepro5** [comment] 2023-06-16 22:46
![image](https://github.com/godot-jolt/godot-jolt/assets/23440295/18234683-cdab-4cea-b58b-80a13a7d623b)
![image](https://github.com/godot-jolt/godot-jolt/assets/23440295/62b9fe04-43a0-4628-974d-078e2c1ac0ac)
So setting this to zero should fix it? It doesn't seem to, and i'm not sure why a rectangular shape would need this kind of optimization. If the issue happened also with rectangular shapes, is that a sign that maybe something else is the cause?

**Comment by Gamepro5** [comment] 2023-06-16 23:02
> Note that this is not the same thing as the margin you set on PhysicsShapeQueryParameters3D, which is more of an extra padding around the cast shape and don't seem to affect the normals as far as I can tell.

If that's so, looking at the description of the Margin property on the shape class, it may be that the reason why I don't observe it working is because this value is the one you were talking about that adds a shell around the object instead of the "inside padding" behavior you so elegantly described.

**Comment by mihe** [comment] 2023-06-17 00:08
> So setting this to zero should fix it?

Yes, assuming that's the problem.

> It doesn't seem to

Not to sound like a broken record, but I'm gonna have to respectfully insist on an actual minimal repro project in that case. I can't debug this over GitHub screenshots, and sifting through hundreds of lines of a character controller that's running around on a big level is not a productive use of either of our time.

Here's an example of one, showing the shape margins affecting the normal: [shape_cast_normals.zip](https://github.com/godot-jolt/godot-jolt/files/11777288/shape_cast_normals.zip)

Feel free to add your failure case to that one and send it back.

> i'm not sure why a rectangular shape would need this kind of optimization

The illustration I stole from Jolt's documentation is that of a box shape, with a very exaggarated convex radius. Boxes, cylinders and convex hulls/polygons all make use of this property. I presume it has something to do with them all having hard edges. Why exactly that is I can't really answer, but convex shapes that are already naturally rounded, like capsules and spheres, don't seem to need this property.

> looking at the description of the Margin property on the shape class

This description was written for the Bullet integration, which as I understand it doesn't integrate the shape margin in the same way as how Jolt does it. So what you're looking at there is in fact the "inside padding", as you describe it. The description of "an extra shell around shapes" is not applicable to Jolt for that particular margin.

**Comment by Gamepro5** [comment] 2023-06-17 01:34
You are correct. I downloaded your MRP and tested it for about an hour, writing a basic character controller to test it out even further. There must be an issue with my custom character controller. I'm sorry for wasting your time. In the future, I'll try to simplify projects down even further so I can make sure something isn't my fault. I'm going to try to figure out what went wrong with my character controller to report such normals. If I can find the issue and fix it on my project, i'll close this issue, but there is still a (small) chance I find something wrong. If I do, I'll be sure to make an even smaller MRP 😅.

**Comment by Gamepro5** [comment] 2023-06-17 03:02
[normal_bug.zip](https://github.com/godot-jolt/godot-jolt/files/11777740/normal_bug.zip)
Nevermind! I was able to isolate it. It seems like ConvexPolygonShape3D might have something to do with it, anyway.

**Comment by mihe** [comment] 2023-06-17 09:01
You left the shape margin for the `ConvexPolygonShape3D` floor at 0.04, which is why you're seeing those kinds of normals there.

When setting it to 0 you get the same jitter of about ~0.5 degrees as in the other (now deleted?) MRP that you made, which used the same CSG collision (i.e. `ConcavePolygonShape3D`) as I did in mine.

Interestingly this slight jitter seems to be related to the `safe_margin` parameter, which is that "extra padding" I mentioned earlier. If I allow this to be 0 (which it normally [is not](https://github.com/godot-jolt/godot-jolt/blob/966d3c135b1cdc4deed23e64516b9b8927e5214e/src/spaces/jolt_physics_direct_space_state_3d.cpp#L494)) then this jitter seems to go away. So it seems my earlier statement about this "extra padding" not affecting normals was incorrect, and might warrant some investigation.

Either way, unless you strictly need the recovery aspect of `move_and_collide`, and you don't need multiple shapes in the cast, then I'd suggest just using a regular `cast_motion` (with no [cast margin](https://docs.godotengine.org/en/latest/classes/class_physicsshapequeryparameters3d.html#class-physicsshapequeryparameters3d-property-margin)) coupled with `get_rest_info` instead, which should eliminate this jitter.

**Comment by Gamepro5** [comment] 2023-06-17 09:26
So if I understand correctly, I would need to make a script that sets the margin of every collision shape for all map geometry to 0 so that it would work with my colliding object that already has it's margin set to 0?

> Interestingly this slight jitter seems to be related to the safe_margin parameter, which is that "extra padding" I mentioned earlier. If I allow this to be 0 (which it normally [is not](https://github.com/godot-jolt/godot-jolt/blob/966d3c135b1cdc4deed23e64516b9b8927e5214e/src/spaces/jolt_physics_direct_space_state_3d.cpp#L494)) then this jitter seems to go away. So it seems my earlier statement about this "extra padding" not affecting normals was incorrect, and might warrant some investigation.

I'm also not sure I understand this. Isn't margin the same as safe_margin?

**Comment by mihe** [comment] 2023-06-17 09:50
> I would need to make a script that sets the margin of every collision shape for all map geometry to 0 so that it would work with my colliding object that already has it's margin set to 0?

Zeroing out the shape margin of the cast/query shape will only stop that particular shape from being "rounded off", so you'd still need to zero out the shape margin for any `BoxShape3D`, `CylinderShape3D` or `ConvexPolygonShape3D` you collide with as well, yes.

If you use `ConcavePolygonShape3D` instead, which is pretty common for static geometry, then you don't need to zero out the margin for it, since it doesn't use this optimization. Godot still includes a `margin` property for it though, which I don't understand, since even the Bullet integration in Godot 3 ignored the margin for anything but boxes, cylinders and convex polygons.

I'll see about maybe adding a project setting that makes the extension ignore the shape margin altogether and just default it to 0 globally. I'm sure more people will get tripped up on this in the future.

> I'm also not sure I understand this. Isn't margin the same as safe_margin?

No. I'm not sure why Godot decided to give these such similar names, but the `margin` property on `Shape3D` will (in Jolt) not extend the shape bounds, and instead only round off any sharp corners. This property is ignored by Godot Physics.

The `margin` property on `PhysicsShapeQueryParameters3D`, which is the exact same thing as `safe_margin` in `move_and_collide` and `test_move`, will extend the query shape's bounds by that amount. This parameter is used by Godot Physics as well, and does the same thing there.

**Comment by Gamepro5** [comment] 2023-06-17 10:07
Okay, thank you for all the useful info! I'm not sure how much this margin property saves on performance, because I truly don't mind it on non characterbody interactions, but if it doesn't really change that much, it would be nice to have a global turn off so I don't need to have the overhead of scanning all shapes and changing their margin to 0.

**Comment by mihe** [comment] 2023-06-17 10:41
> I'm not sure how much this margin property saves on performance.

Yeah, I don't know the answer to that, unfortunately. I suspect it becomes more relevant for complex convex polygons, or very large quantities of the applicable shapes.

Anyway, I'll go ahead and close this again then, since there's not really any showstoppers here other than unfortunate UX, and perhaps lacking documentation on my part. I'll see if I can maybe make this clearer in the README somehow. It's a lot to unpack though, as you can tell.

I'll create a separate issue for the slight jitter caused by `safe_margin`. I suspect I'll need to forward that one upstream to Jolt.

I've also added the project setting for disabling shape margins to my TODO list, so expect to see that in the changelog of an upcoming release.

**Closed by mihe** 2023-06-17 10:41 UTC
Labels: needs triage
