### ISSUE TITLE
Multiple CollisionShapes pass through HeightMapShape

### ISSUE THREAD

**Issue by TokisanGames** [godot-jolt/godot-jolt#1007] opened 2024-10-30 19:12 UTC
Jolt 0.13
Terrain3D 0.9.3
Godot 4.3, 4.4dev3

I just tried the latest version of Jolt w/ Terrain3D and found that our player configuration with two collision shapes doesn't work reliably. It works fine with Godot physics and older versions of Jolt. I've had two others confirm this on their systems.

Player construction has a SeparationRay to allow the character to smoothly float over the ground bumps. The chest is a capsule to prevent the player from passing through walls.

![Godot_v4 3-stable_win64_WTE1tQdCe7](https://github.com/user-attachments/assets/ea1caf9e-cae2-4803-b438-dbb7ce63e728)

![{96C68F8E-B8E3-4068-ABA6-70512B268134}](https://github.com/user-attachments/assets/f66ac031-7a0c-472d-af4a-02b9ff494129)

With this configuration in Jolt, the player has no issue with the ground and cannot push through it. However, it takes only a minor amount of speed to punch through a wall of the HeightMapShape. The capsule shape is supposed to prevent that but is failing with minor resistance. If the Separation ray is disabled, so only the capsule shape is active, it works properly and I can't get it to pass through the HeightMapShape.

![{CAFD8A3B-6C01-4227-9D9E-FEFF9BCF2423}](https://github.com/user-attachments/assets/21a9899e-c769-44bc-831d-570d13705f01)

Here is the player code:
https://github.com/TokisanGames/Terrain3D/blob/main/project/demo/src/Player.gd

### To Reproduce:
* Install Jolt 0.13.
* Install Terrain3D from the asset lib.
* Run the demo.
* In the first valley run from one side to the other and the player will pop through. There are other walls throughout the demo the player can run through with only moderate speed.
* Edit the player and disable `CollisionShapeRay`, and repeat the experiment.

To see debug collision, enable it in the godot menu, and enable `Terrain3D / Collision / Collision Mode = Full / Editor`.

**Comment by mihe** [comment] 2024-10-31 17:51
This looks to be a duplicate of #945, which was fixed in #949, but I haven't cut a new release with the fix yet.

You can work around this for the time being by disabling the `physics/jolt_3d/collisions/use_enhanced_internal_edge_removal` project setting.

This manifestation of the issue looks pretty bad though. I'll see if I can finally take the time this weekend to cut a new release. I've been pushing it in front of me for way too long now.

**Closed by mihe** 2024-10-31 17:51 UTC
Labels: bug, duplicate, topic:runtime, severity:minor

**Comment by mihe** [comment] 2024-11-03 18:27
The fix for this can now be found in the newly released [0.14.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable).

Note that the release on Godot Asset Library is still pending approval, so you might need to download it from GitHub for the time being.

**Comment by TokisanGames** [comment] 2024-11-03 21:09
Thanks!
