### ISSUE TITLE
Spikes in processing time causes lower perfomance on Android with simple triple match game. 

### ISSUE THREAD

**Issue by felipejfc** [godot-jolt/godot-jolt#982] opened 2024-09-19 15:21 UTC
I'm developing a triple-match/match factory like game and usage of physics is very simple in it, couple objects on the screen colliding with each other.

When running the game on Android and profiling Jolt vs Default godot engine, we found that Jolt has multiple spikes in processing time, which harm visuals of the game while the default engine (running on a separate thread) works perfectly.

Jolt:

![image](https://github.com/user-attachments/assets/6124e626-f7f6-47bd-a904-7dbec7430c1d)

Default:

<img width="693" alt="image" src="https://github.com/user-attachments/assets/7e334749-06da-47df-b123-00ee169c3e71">

I got the same results on both High "Endish" devices like Pixel 6A and low end ones like Galaxy S8.

**Comment by mihe** [comment] 2024-09-19 15:27
> while the default engine (running on a separate thread) works perfectly

What about Godot Physics without running it on a separate thread?

**Comment by felipejfc** [comment] 2024-09-19 17:27
Godot Physics on default thread:

<img width="973" alt="image" src="https://github.com/user-attachments/assets/5a4e1fb8-b2bf-4497-97ea-d5e861629a1a">

Definitely worse than running separate, framerate becomes more unstable, however, we still can't see spikes like Jolt is presenting

**Comment by felipejfc** [comment] 2024-09-19 17:31
Providing additional info, this step seems to be the main offender when using Jolt:

![image](https://github.com/user-attachments/assets/e2d72dcc-c782-42e3-bcdb-d5558fe2908c)

**Comment by mihe** [comment] 2024-09-19 17:47
Interesting.

Any chance you'd be able to provide some kind of repro project/scene?

**Comment by mihe** [comment] 2024-09-20 04:31
@jrouwe I realize there's not a lot to go by here, but do you have any theories as to what kind of circumstances could be causing the `SolveVelocityConstraint` job to be spiking like this?

**Comment by jrouwe** [comment] 2024-09-20 12:20
SolveVelocityConstraints will spike when:
* An object touches another complex object, usually a mesh or heightfield (what is your static geometry like?)
* There is a very large island (a group of touching bodies), although I wouldn't count 40 as large
* You have a high value in the settings for 'Solver' / 'Velocity Iterations'

**Comment by felipejfc** [comment] 2024-09-20 21:10
Solver/Velocity Iterations is set to 10
There's definitely bunch of touching bodies but at most 60 I would say. And when there are less I can see that the spikes happen less frequently
objects are not super complex, some colliders in form of fruits or objects

**Comment by mihe** [comment] 2024-09-20 21:23
It doesn't sound like there's any obvious culprit here.

@felipejfc Any chance you could construct some type of minimal repro project that mimics the setup in your actual project? It's going to be difficult to pinpoint your exact problem without some way of reproducing it on our end.

**Comment by felipejfc** [comment] 2024-09-21 21:30
I will try to create a minimal repro

**Comment by mihe** [comment] 2024-10-17 09:48
@felipejfc Were you ever able to create some sort of minimal repro for this?

**Comment by mihe** [comment] 2024-12-20 14:47
Closing this as "cannot reproduce".

Note that this extension has now been merged into Godot in the form of an engine module, where the `physics/3d/run_on_separate_thread` project setting is supported. If you're able/willing to try your project there instead (in the just recently released [4.4-dev7](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-7/)) I'd be curious to hear if you experience the same problems there still.

**Closed by mihe** 2024-12-20 14:47 UTC
Labels: topic:runtime, performance
