### ISSUE TITLE
Can't load extension on 4.2.dev5 or custom dev build

### ISSUE THREAD

**Issue by thygrrr** [godot-jolt/godot-jolt#627] opened 2023-10-02 09:24 UTC
Heads-up, apparently, godot-jolt doesn't load correctly on 4.2 (causes a crash).

The crash is immediate, e.g. right after downloading the extension from the official Asset Library; but it also applies to 0.8 downloaded from here.

The 0.8 and Asset Library releases seem to be working in order in 4.1.2.rc1 and 4.1.1.stable.

It's possible GDExtension has some breaking changes in 4.2, perhaps you may want to investigate.

There is no discernible console output on 4.2.dev5 possibly due to how the process forks itself.

There's no useful debug info coming anyway. I can only get output from a local build, but it, too, isn't very helpful.

```
(gdb) target exec c:/Tools/godot/Godot_v4.2-dev5_win64_console.exe
(gdb) run -e --path C:/Projects/spacedog-godot
Starting program: c:\Tools\godot\Godot_v4.2-dev5_win64_console.exe -e --path C:/Projects/spacedog-godot
[New Thread 60876.0xedd4]
[New Thread 60876.0xedd8]
[New Thread 60876.0xeddc]
Godot Engine v4.2.dev5.official.e3e2528ba - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080

[Thread 60876.0xeddc exited with code 3221225477]
[Thread 60876.0xedd8 exited with code 3221225477]
[Thread 60876.0xedd4 exited with code 3221225477]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by mihe** [comment] 2023-10-02 09:52
Duplicate of #600.

**Closed by mihe** 2023-10-02 09:52 UTC
Labels: wontfix, topic:usage

**Comment by thygrrr** [comment] 2023-10-05 09:54
Sorry, I had misinterpreted the statement that 4.1 extensions should work in 4.2; thank you for clarifying in #600 

Thanks a lot for the great work on this extension!
