### ISSUE TITLE
Scene is slow when using many bodies/shapes

### ISSUE THREAD

**Issue by albinaask** [godot-jolt/godot-jolt#657] opened 2023-10-26 16:17 UTC
So, regarding the #656 I'll share my test case and have this weird frame rate drop... it starts fine and then quickly drops down to 6 FPS and sits there for like 1600 frames, then it all suddenly clears up in just a few frames and everything is just fine at 60FPS... It seems not to clear up when sleeping is turned off, which is not surprising...

What's odd is that the CPU is basically not working according to windows task manager and godot, it sits happily around at 14% of which 7% is godot... I would expect an optimized, heavy CPU bound task written in C++ would strain the CPU to a far greater extent.

When I look at the profiler, I find that godot thinks it uses ~50ms per frame to render which should equate to an FPS of 20, while it also registers an FPS of 2, which is the accurate figure with the experience...
![bild](https://github.com/godot-jolt/godot-jolt/assets/11806563/d46efac3-ca61-4cc4-85c5-83db56051670)

This image sais that physics time is 300% of 60 FPS, which would correspond to 20FPS, while the frame time is 2000%, which corresponds to reality...so I don't really know what is up...
![bild](https://github.com/godot-jolt/godot-jolt/assets/11806563/316b2eb3-d3d5-4956-a29e-280a2d4e0d86)

Then I look at godot's profiler I get that like all of the time is spent in the yellow color like below:
![bild](https://github.com/godot-jolt/godot-jolt/assets/11806563/221483cc-d93c-4c25-b20d-977c35327226)
The odd thing is that that color isn't mapped to anything as far as I can see...

What is so odd to me is that there is only ever one body... There should be 0 collision querying...

The test case that is attached generates adds all the shapes to one body at _ready(), which is also quite slow... So you should perhaps think about not rebuilding the tree until the very last thing before the first frame since the current setup rebuilds it like 15k times in this setup if I didn't misunderstood you. Furthermore there seem to be no real difference between cubes and prism convex hulls. 

(removed the macos binaries in order to shrink prj to fit github's max file size...)
[prj.zip](https://github.com/godot-jolt/godot-jolt/files/13180296/prj.zip)

**Comment by mihe** [comment] 2023-10-26 22:01
I can't seem to be able to reproduce the initial FPS drop you mention.

When the body is sleeping I get about 450 FPS (2.22 ms) and when it's not I get about 220 FPS (4.55 ms). The sleeping happens pretty quickly though, given that the sleep threshold is left at the default of 0.5 seconds, so I can't imagine that it accounts for the 1600 slow frames you're seeing.

I can't seem to even start Godot's profiler in this scene if I try to start it during the splash screen, as the process just crashes right when the splash screen is meant to disappear. Frankly I struggle to understand Godot's profiler for the most part, so I try to stick to external profilers instead, and when running this scene through Superluminal I can't really see anything out of the ordinary, besides the incredibly long loading/initialization time.

> What's odd is that the CPU is basically not working according to windows task manager and godot, it sits happily around at 14% of which 7% is godot... I would expect an optimized, heavy CPU bound task written in C++ would strain the CPU to a far greater extent.

The task manager considers 100% CPU usage to be when all CPU cores are saturated. If you're running full blast on a single core (like when recreating the compound shape thousands of times over) you'll only ever see `100 / total_logical_cores` percentage of CPU usage.

> The test case that is attached generates adds all the shapes to one body at _ready(), which is also quite slow... So you should perhaps think about not rebuilding the tree until the very last thing before the first frame since the current setup rebuilds it like 15k times in this setup if I didn't misunderstood you.

I did explore the possibility of lazily rebuilding the compound shape in a more aggressive way than I do currently, but it's unfortunately quite error-prone, as there are plenty of operations that would require the latest up-to-date compound shape, meaning I would need to identify all of those and force a rebuild in those cases anyway, which (assuming I could even identify them all) would just lead to other (albeit lesser) unintuitive performance pitfalls.

The better solution would be to somehow offer the option to instead use Jolt's `MutableCompoundShape` and mutate that as-needed. It's something I've been meaning to do for a while but haven't gotten around to yet.

The workaround in this case is just moving the `add_child(node)` call in `spawn_instance` to the bottom of that function, which will make it so the shapes are only ever added _before_ the body is added to the scene tree (i.e. the physics simulation) and thus the compound shape is only ever created once.

I'd be curious to know if moving that `add_child(node)` call solves your initial FPS drop as well.

**Comment by albinaask** [comment] 2023-10-27 13:16
I'll have a go at it. The problem is that I in my case will need to add shapes at runtime, so this feature would help me a lot.

What processor are you running? It seem to be fine up until a certain number of shapes for me, then quickly drop off. What OS are you running? Could it be something with the different builds that means that it doesn't utilize the multiprocessing capacity of my CPU? I'll try to run it inside another profiler if I can find one that likes me using the prebuilt gdextension variant, otherwise I'll probably have to make an extensive setup with cloning the repo, rebuilding it in some sort of custom environment I'm not familiar with etc...

**Comment by albinaask** [comment] 2023-10-27 13:20
If you crank up the dimensions in the test case to like 122, and set the num_of_blocks to 1, what happends to your CPU usage in your resource manager? Because mine never seem to go above the aforementioned 7% enven though I throw a lot of bodies at it and the FPS tanks.

**Comment by mihe** [comment] 2023-10-27 15:18
> The problem is that I in my case will need to add shapes at runtime, so this feature would help me a lot.

If you're trying to make some sort of voxel-based thing then it's probably a better idea to chunk using separate bodies instead and add/remove those as-needed, which can then have their shapes be added while they're outside the scene tree. In any case, this is not something that's likely to be addressed near-term.

> What processor are you running?
> What OS are you running?

AMD 3700X on Windows.

> if I can find one that likes me using the prebuilt gdextension variant

The debug symbols are available to download for every [GitHub release](https://github.com/godot-jolt/godot-jolt/releases), so you shouldn't need to build anything from source to profile.

> If you crank up the dimensions in the test case to like 122, and set the num_of_blocks to 1, what happends to your CPU usage in your resource manager?

This will create almost 15k dynamic bodies that are all touching eachother, which is not only pushing things quite a bit in terms of number of bodies but will also blow up a lot of the other (configurable) limits in Jolt, like "Max Body Pairs", "Max Contact Constraints" and potentially "Max Temporary Memory" as well, which you should see warnings about in Godot's Debugger output.

I think I managed to reproduce something similar-ish to what you're seeing. If I create 75 dynamic (but stationary) bodies with 75 shapes each (i.e. 5625 boxes in total), but with `add_child(node)` at the bottom of `spawn_instance`. When I start that up I see the initial `_ready` call take up almost 12 seconds, 8 seconds of which is spent just instantiating scenes and nodes, and over 5 seconds of that is solely spent allocating memory. Then once that's all done you get a couple of incredibly slow frames due to the transform propagation that has to happen between the scene nodes once the bodies' transforms are synchronized from the physics server. This then seems to settle down after a while, presumably due to the bodies going to sleep.

All-in-all, I'm not really seeing anything here that can be attributed to this extension per se, and instead it seems to mostly be related to the scene nodes, all of which happens on a single thread. Rendering this amount of meshes in a non-instanced manner is quite expensive as well, and dwarves the physics simulation by quite a bit.

Also, how exactly are you measuring this frame rate drop? I noticed you bundled the [Debug Menu](https://godotengine.org/asset-library/asset/1902) add-on, which seems to do some kind of smoothing/averaging of its frame rate counter. This seems to make it report a quite low frame rate in the first second or two, for reasons I don't quite understand. If that's what you're looking at then you might be better off looking at the millisecond counter below the frame rate, which doesn't seem to be smoothed/averaged.

**Comment by albinaask** [comment] 2023-10-27 18:54
This seem to have fixed things!

**Comment by mihe** [comment] 2023-10-27 20:24
> This seem to have fixed things!

What did?

**Comment by albinaask** [comment] 2023-10-27 22:12
Removing all the scene tree stuff...

**Comment by mihe** [comment] 2023-10-28 10:33
Alright, I'll go ahead and close this then.

I made a separate issue (#660) for the in-tree shape manipulation stuff, since it got sort of mixed up with the scene stuff in this issue.

**Closed by mihe** 2023-10-28 10:33 UTC
Labels: topic:runtime, performance
