### ISSUE TITLE
JoltPhysicsDirectSpaceState3D cannot set_exclude when intersect ray

### ISSUE THREAD

**Issue by hakuhan** [godot-jolt/godot-jolt#1006] opened 2024-10-27 05:41 UTC
Hi! I upgrade from godot physics to Jolt physics. Most of the physics parts work better and faster in my project. But I found one simple issue which is set_exlude feature is missing in jolt.
In godot physics: 
```

Dictionary PhysicsDirectSpaceState3D::_intersect_ray(const Ref<PhysicsRayQueryParameters3D> &p_ray_query) {
	ERR_FAIL_COND_V(!p_ray_query.is_valid(), Dictionary());

	RayResult result;
	bool res = intersect_ray(p_ray_query->get_parameters(), result);

	if (!res) {
		return Dictionary();
	}

	Dictionary d;
	d["position"] = result.position;
	d["normal"] = result.normal;
	d["face_index"] = result.face_index;
	d["collider_id"] = result.collider_id;
	d["collider"] = result.collider;
	d["shape"] = result.shape;
	d["rid"] = result.rid;

	return d;
}
```

and

```
class PhysicsRayQueryParameters3D : public RefCounted {
	GDCLASS(PhysicsRayQueryParameters3D, RefCounted);

	PhysicsDirectSpaceState3D::RayParameters parameters;

protected:
	static void _bind_methods();

public:
	static Ref<PhysicsRayQueryParameters3D> create(Vector3 p_from, Vector3 p_to, uint32_t p_mask, const TypedArray<RID> &p_exclude);
	const PhysicsDirectSpaceState3D::RayParameters &get_parameters() const { return parameters; }

	void set_from(const Vector3 &p_from) { parameters.from = p_from; }
	const Vector3 &get_from() const { return parameters.from; }

	void set_to(const Vector3 &p_to) { parameters.to = p_to; }
	const Vector3 &get_to() const { return parameters.to; }

	void set_collision_mask(uint32_t p_mask) { parameters.collision_mask = p_mask; }
	uint32_t get_collision_mask() const { return parameters.collision_mask; }

	void set_collide_with_bodies(bool p_enable) { parameters.collide_with_bodies = p_enable; }
	bool is_collide_with_bodies_enabled() const { return parameters.collide_with_bodies; }

	void set_collide_with_areas(bool p_enable) { parameters.collide_with_areas = p_enable; }
	bool is_collide_with_areas_enabled() const { return parameters.collide_with_areas; }

	void set_hit_from_inside(bool p_enable) { parameters.hit_from_inside = p_enable; }
	bool is_hit_from_inside_enabled() const { return parameters.hit_from_inside; }

	void set_hit_back_faces(bool p_enable) { parameters.hit_back_faces = p_enable; }
	bool is_hit_back_faces_enabled() const { return parameters.hit_back_faces; }

	void set_exclude(const TypedArray<RID> &p_exclude);
	TypedArray<RID> get_exclude() const;
};
```
then

```
Dictionary PhysicsDirectSpaceState3D::_intersect_ray(const Ref<PhysicsRayQueryParameters3D> &p_ray_query) {
	ERR_FAIL_COND_V(!p_ray_query.is_valid(), Dictionary());

	RayResult result;
	bool res = intersect_ray(p_ray_query->get_parameters(), result);

	if (!res) {
		return Dictionary();
	}

	Dictionary d;
	d["position"] = result.position;
	d["normal"] = result.normal;
	d["face_index"] = result.face_index;
	d["collider_id"] = result.collider_id;
	d["collider"] = result.collider;
	d["shape"] = result.shape;
	d["rid"] = result.rid;

	return d;
}
```

In Jolt:

```
bool JoltPhysicsDirectSpaceState3D::_intersect_ray(
	const Vector3& p_from,
	const Vector3& p_to,
	uint32_t p_collision_mask,
	bool p_collide_with_bodies,
	bool p_collide_with_areas,
	bool p_hit_from_inside,
	bool p_hit_back_faces,
	bool p_pick_ray,
	PhysicsServer3DExtensionRayResult* p_result
) {
	space->try_optimize();

	const JoltQueryFilter3D query_filter(
		*this,
		p_collision_mask,
		p_collide_with_bodies,
		p_collide_with_areas,
		p_pick_ray
	);

	const JPH::RVec3 from = to_jolt_r(p_from);
	const JPH::RVec3 to = to_jolt_r(p_to);
	const auto vector = JPH::Vec3(to - from);
	const JPH::RRayCast ray(from, vector);

	const JPH::EBackFaceMode back_face_mode = p_hit_back_faces
		? JPH::EBackFaceMode::CollideWithBackFaces
		: JPH::EBackFaceMode::IgnoreBackFaces;

	JPH::RayCastSettings settings;
	settings.mTreatConvexAsSolid = p_hit_from_inside;
	settings.mBackFaceModeTriangles = back_face_mode;

	if (JoltProjectSettings::use_legacy_ray_casting()) {
		settings.mBackFaceModeConvex = back_face_mode;
	}

	JoltQueryCollectorClosest<JPH::CastRayCollector> collector;

	space->get_narrow_phase_query()
		.CastRay(ray, settings, collector, query_filter, query_filter, query_filter);

	if (!collector.had_hit()) {
		return false;
	}

	const JPH::RayCastResult& hit = collector.get_hit();

	const JPH::BodyID& body_id = hit.mBodyID;
	const JPH::SubShapeID& sub_shape_id = hit.mSubShapeID2;

	const JoltReadableBody3D body = space->read_body(body_id);
	const JoltObjectImpl3D* object = body.as_object();
	ERR_FAIL_NULL_D(object);

	const JPH::RVec3 position = ray.GetPointOnRay(hit.mFraction);

	JPH::Vec3 normal = JPH::Vec3::sZero();

	if (!p_hit_from_inside || hit.mFraction > 0.0f) {
		normal = body->GetWorldSpaceSurfaceNormal(sub_shape_id, position);

		// HACK(mihe): If we got a back-face normal we need to flip it
		if (normal.Dot(vector) > 0) {
			normal = -normal;
		}
	}

	p_result->position = to_godot(position);
	p_result->normal = to_godot(normal);
	p_result->rid = object->get_rid();
	p_result->collider_id = object->get_instance_id();
	p_result->collider = object->get_instance_unsafe();
	p_result->shape = 0;

	if (const JoltShapedObjectImpl3D* shaped_object = object->as_shaped()) {
		const int32_t shape_index = shaped_object->find_shape_index(sub_shape_id);
		ERR_FAIL_COND_D(shape_index == -1);
		p_result->shape = shape_index;
		p_result->face_index = _try_get_face_index(*body, sub_shape_id);
	}

	return true;
}
```

**Comment by mihe** [comment] 2024-10-28 11:32
I'm not sure I understand the problem exactly. Exclusions are implemented for `intersect_ray`, and should work just like in Godot Physics. They are however done a bit differently in GDExtension compared to how they're done in Godot itself. You'll find the filtering code here:

https://github.com/godot-jolt/godot-jolt/blob/ccc7b394f203460a3eeb37e8b12a93958f72ddd7/src/spaces/jolt_query_filter_3d.cpp#L60-L65

`PhysicsDirectSpaceState3DExtension::is_body_excluded_from_query` checks against a thread-local static `HashSet<RID>` on the Godot side of things, as seen [here](https://github.com/godotengine/godot/blob/a3080477ac0421aef24ca0916c40559abbf4846b/servers/extensions/physics_server_3d_extension.cpp#L33-L35).

What symptoms are you seeing exactly, and would you be able to provide some sort of reproduction project that showcases the problem?

**Comment by hakuhan** [comment] 2024-10-30 02:59
Hi! Thanks for reply! Here's my cases:
I used `intersect_ray` in gdextension and pass a `set_exclude` in `PhysicsRayQueryParameters3D `. 
There are few areas attached to my character. And I have few logics to check ray ok or not at runtime. If the checking logic returns false I will add collision shape RID to my next `intersect_ray` checking to make sure inside area should be detected next time (And also I modified few codes in godot physics to make sure it works ok
![图片](https://github.com/user-attachments/assets/bbbae6e5-9562-4ac3-af77-cae5d6760ae6)
). 
I tried to create a new `interect_ray` when current ray stoped at a failed area instead of `set_exclude.` But the result of creating new one is worse than `set_exclude` version. I think the reason is that it may cast on first area if I set a sort start point in next `intersect_ray`. If I set next start point longer inside area may losing in new ray.
With these cases I used `set_exclude` in my project.

**Comment by mihe** [comment] 2024-10-31 20:33
So based on your screenshot I assume you want the ability to use the `exclude` parameter not only for `CollisionObject3D` RIDs, but also `Shape3D` RIDs? If so, then applying this patch on latest `master` of this extension (ccc7b39 as of writing this) should do the trick:

```patch
diff --git a/src/spaces/jolt_physics_direct_space_state_3d.cpp b/src/spaces/jolt_physics_direct_space_state_3d.cpp
index 8b584d3758..9bb30730b0 100644
--- a/src/spaces/jolt_physics_direct_space_state_3d.cpp
+++ b/src/spaces/jolt_physics_direct_space_state_3d.cpp
@@ -56,7 +56,7 @@ bool JoltPhysicsDirectSpaceState3D::_intersect_ray(
 	JoltQueryCollectorClosest<JPH::CastRayCollector> collector;
 
 	space->get_narrow_phase_query()
-		.CastRay(ray, settings, collector, query_filter, query_filter, query_filter);
+		.CastRay(ray, settings, collector, query_filter, query_filter, query_filter, query_filter);
 
 	if (!collector.had_hit()) {
 		return false;
diff --git a/src/spaces/jolt_query_filter_3d.cpp b/src/spaces/jolt_query_filter_3d.cpp
index 92effe58e2..acb4f3a37c 100644
--- a/src/spaces/jolt_query_filter_3d.cpp
+++ b/src/spaces/jolt_query_filter_3d.cpp
@@ -1,6 +1,8 @@
 #include "jolt_query_filter_3d.hpp"
 
 #include "objects/jolt_object_impl_3d.hpp"
+#include "objects/jolt_shaped_object_impl_3d.hpp"
+#include "shapes/jolt_shape_impl_3d.hpp"
 #include "spaces/jolt_broad_phase_layer.hpp"
 #include "spaces/jolt_physics_direct_space_state_3d.hpp"
 #include "spaces/jolt_space_3d.hpp"
@@ -63,3 +65,23 @@ bool JoltQueryFilter3D::ShouldCollideLocked(const JPH::Body& p_body) const {
 	return (!picking || object->is_pickable()) &&
 		!space_state.is_body_excluded_from_query(object->get_rid());
 }
+
+bool JoltQueryFilter3D::ShouldCollide(
+	const JPH::Shape* p_shape2,
+	const JPH::SubShapeID& p_sub_shape_id2
+) const {
+	if (p_shape2->GetType() == JPH::EShapeType::Compound) {
+		return true;
+	}
+
+	const JoltReadableBody3D body = space.read_body(mBodyID2);
+	ERR_FAIL_COND_D(body.is_invalid());
+
+	if (const JoltShapedObjectImpl3D* shaped_object = body.as_shaped()) {
+		if (const JoltShapeImpl3D* shape = shaped_object->find_shape(p_sub_shape_id2)) {
+			return !space_state.is_body_excluded_from_query(shape->get_rid());
+		}
+	}
+
+	return false;
+}
diff --git a/src/spaces/jolt_query_filter_3d.hpp b/src/spaces/jolt_query_filter_3d.hpp
index 50d4d5e8a0..72853555f4 100644
--- a/src/spaces/jolt_query_filter_3d.hpp
+++ b/src/spaces/jolt_query_filter_3d.hpp
@@ -6,7 +6,8 @@ class JoltSpace3D;
 class JoltQueryFilter3D final
 	: public JPH::BroadPhaseLayerFilter
 	, public JPH::ObjectLayerFilter
-	, public JPH::BodyFilter {
+	, public JPH::BodyFilter
+	, public JPH::ShapeFilter {
 public:
 	JoltQueryFilter3D(
 		const JoltPhysicsDirectSpaceState3D& p_space_state,
@@ -24,6 +25,8 @@ public:
 
 	bool ShouldCollideLocked(const JPH::Body& p_body) const override;
 
+	bool ShouldCollide(const JPH::Shape* p_shape2, const JPH::SubShapeID& p_sub_shape_id2) const;
+
 private:
 	const JoltPhysicsDirectSpaceState3D& space_state;
```

I haven't tested it very thoroughly, so there might be some problems with it, but that should help get you started at least.

Since the `exclude` parameter explicitly states in Godot's documentation that it's meant for `CollisionObject3D` RIDs I'll go ahead and close this.

**Closed by mihe** 2024-10-31 20:33 UTC
Labels: enhancement, wontfix, topic:runtime

**Comment by hakuhan** [comment] 2024-11-02 03:08
Hi! @mihe  Sorry for ask again! Could you please give me a notice. How can I get mBodyID2 from `const JPH::Shape* p_shape2 or const JPH::SubShapeID& p_sub_shape_id2` these parameters?
