### ISSUE TITLE
Shapecasting parallel/near-parallel to angled surfaces consistently results in bad collision safe fractions

### ISSUE THREAD

**Issue by MarioBossReal** [godot-jolt/godot-jolt#755] opened 2024-01-23 22:36 UTC
This isn't the easiest issue to explain but I'll do my best. I've written a custom character controller which purely uses shapecasting for its collision testing. It relies heavily on getting the safe collision fraction of the shape cast in order to determine how far it can safely travel without getting stuck in geometry.

For the most part, this works almost flawlessly, as I will demonstrate in the video below. Even when completely disabling stuck checking and resolving (checking if the player is stuck and then teleporting them to a safe position), the shapecast results keep the player within bounds to a very good degree.

Where it fails however, is when shapecasting along ramped surfaces. I've found that shapecasting in a direction parallel or near-parallel to an angled surface will consistently result in a bad collision fraction, (the collision fraction is larger than it should be and results in the player clipping through geometry). This happens when casting with all primitive colliders, and from my testing the box collider seems to fair the best, with capsule coming next and with cylinder having the worst results (though this is to be expected in any case). The issue is the same whether casting against a primitive, hull, or mesh.

I also tested to see if the shape cast was returning bad normals but from what I could see all the normals are correct. It seems the issue is with the precision of the shapecast's collision resolution when being swept along near-parallel surfaces (the issue does very occasionally happen when sweeping parallell and close to a normal wall, but this happening occasionally is not an issue).

For reference, the only default setting I've changed is to disable "Use Shape Margins". All shapecasts are performed with a margin of 0 (using margins makes collisions inconsistent and not very usable).

https://www.youtube.com/watch?v=-iEvzG_RILY

This video demonstrates the issue with stuck-resolving/unsticking completely disabled. The character's bounding box is highlighted in purple when under safe conditions, and in red when it is in a stuck condition.

First section of the video demonstrates good collision resolution against 90 degree walls.
Second section demonstrates issue when sliding on ramp.
Third section demonstrates bunnyhopping into the underside of the ramp (no/minimal issue) versus walking under the ramp parallel to the surface (immediate and consistent clipping).

Edit: For further reference, this issue does happen in GodotPhysics to a considerably worse degree, and in general GodotPhysics returns pretty much unusable collision fractions in most situations.

**Comment by mihe** [comment] 2024-01-23 22:52
I'd appreciate a minimal reproduction project of some sort.

**Comment by MarioBossReal** [comment] 2024-01-24 00:15
I uploaded an MRP and sent you an invite. The MRP has two scenes, a test scene and a player scene. I ended up including the player scene because I found it difficult to reproduce the issue when doing single / few shapecasts over larger distances. This might mean that its a floating point precision issue, as the player has to shapecast along multiple short bounces. Im now not entirely sure what the cause of the issue is but I hope the MRP will help out.

**Comment by mihe** [comment] 2024-01-24 01:13
> I ended up including the player scene because I found it difficult to reproduce the issue when doing single / few shapecasts over larger distances.

Respectfully, this scene has to be broken down into the actual problematic shape-casts by somebody one way or another, assuming they are indeed the culprit, and frankly I'd rather not spend the time doing it.

Character controllers tend to be messy, and this seems to be no exception, especially with the several layers of abstractions for your physics queries. The chance of the problem being either in the character controller itself or in not taking some limitation of Godot into account is presumably non-zero here.

I don't know if this helps in any way, but keep in mind that shape-casts in Godot don't detect initial overlaps, so you have to do some type of initial intersection check to see whether your shape is overlapping with anything at the start, otherwise the shape-cast will ignore that overlap and go right through it.

**Comment by MarioBossReal** [comment] 2024-01-24 01:21
Sorry about that, I'll keep trying to find the root trigger/cause of the issue and if I find anything I will post it here. My suspicion is that it could possibly be caused by precision issues when adding/subtracting position vectors. In the MRP I disabled unsticking but kept the overlap checks for visuals. I noticed that the overlap checks seem to be quite accurate, but since Godot doesn't natively give the safe end point of a shapecast, it has to be calculated using origin + direction * fraction which might cause precision issues.

**Comment by mihe** [comment] 2024-01-24 01:46
> I noticed that the overlap checks seem to be quite accurate

Unless you also omitted those from the MRP, I don't see any actual overlap checks in your code. Doing a sweep/cast with the same from/to position like you do in the `Unstick` method will still exhibit the same problem of ignoring initial overlaps.

This whole thing of creating global nodes derived from `ShapeCast3D` etc. is a bit of a roundabout way of doing queries in Godot. You're likely better off (both from a sanity and performance perspective) to just go straight to the source and use `PhysicsDirectSpaceState3D` instead, i.e. `get_world_3d().direct_space_state`, which is what nodes like `ShapeCast3D` uses under the hood. There you'll find queries like `collide_shape`, `intersect_shape` and `get_rest_info` for doing intersection tests, which all (confusingly) largely do the same thing with some minor differences in their output.

Anyway, I'll go ahead and close this for now. I'll re-open it if/when you find something more concrete.

**Closed by mihe** 2024-01-24 01:46 UTC
Labels: topic:runtime

**Comment by MarioBossReal** [comment] 2024-01-24 02:27
> Doing a sweep/cast with the same from/to position like you do in the Unstick method will still exhibit the same problem of ignoring initial overlaps.

I didn't know this was the case, but if this is true then how come I am seemingly able to detect overlaps by doing so? Are these overlaps not completely accurate compared to using intersect_shape? I'm a bit confused in that regard, although I do understand that sweeping from point A to point B will not detect initial overlaps. As far as using static nodes versus PhysicsDirectSpaceState, it's mostly a C# performance thing as the C# integration does a lot of GC allocations and requires use of a dictionary to retreive results, so I wanted to avoid it as much as possible. I believe that this is to be changed at some point but I also wish that every feature was exposed within nodes as well, seems like a bit of an arbitrary exclusion on Godot's part.

**Comment by MarioBossReal** [comment] 2024-01-24 03:19
According to [shape_cast_3d.cpp](https://github.com/godotengine/godot/blob/master/scene/3d/shape_cast_3d.cpp), `get_rest_info()` is called as part of its `force_shapecast_update()` call. I don't see how this would be different to calling it directly from PhysicsDirectSpaceState3D. The sweeping motion of the shapecast is entirely ignored if the shapecast's target position is Vector3.Zero.

**Comment by MarioBossReal** [comment] 2024-01-24 08:35
Update: I have updated the MRP and have been able to produce the bug with a minimal setup. (I also removed the Character Controller stuff).

Rationale: Shapecasting from a known safe position should return a safe fraction which when applied to the safe position should also result in a new safe position.

Observations: This appears to not always happen especially when sliding on ramped surfaces. A new observation is that when the shapecast returns a bad fraction, the fraction value appears to *always* be either 0 or 1 exactly.

**Comment by mihe** [comment] 2024-01-24 15:49
> The sweeping motion of the shapecast is entirely ignored if the shapecast's target position is Vector3.Zero. According to the documentation setting TargetPosition to Vector3.Zero allows for immediate collision overlaps.

Ah, I had missed that `ShapeCast3D` accounted for this. That's my bad. That's clearly fine then.

> As far as using static nodes versus PhysicsDirectSpaceState, it's mostly a C# performance thing as the C# integration does a lot of GC allocations and requires use of a dictionary to retreive results, so I wanted to avoid it as much as possible.

Right, fair enough.

> Update: I have updated the MRP and have been able to consistently produce the bug with a minimal setup. (I also removed the Character Controller stuff).

Thank you, that's a lot more manageable.

I made some changes in order to rule out certain domains and simplify debugging a bit (see the [`without-sharptrace`](https://github.com/MarioBossReal/jolt-fraction-mrp/tree/without-sharptrace) branch), and it does seem like this is just a case of floating-point precision causing disagreements between `cast_motion` and `get_rest_info`.

Typically I'm seeing the initial overlap check saying there is no collision, but then the initial overlap check in `cast_motion` will say that there is one, causing it to ignore that overlap and yield a safe fraction of 1, which will then cause problems. The penetration depth for all of these problematic collisions is in the order of `2.45756240e-07`, so well within the margin of error for 32-bit floating points. There's a ton of operations/transformations happening under the hood (especially for `cast_motion`) that will help provoke these types of floating-point errors.

I'm no expert on character controllers, but I believe these types of problems is part of the reason why you use some type of "safe margin" (or whatever you want to call it) during certain parts of the move. Godot Physics' own version of this, meaning `body_test_motion`/`move_and_collide`, is certainly not without its own issues, but it goes something like this:

1. Iterative depenetration using overlap checks with the safe margin, which defaults to 0.001.
2. Shape-cast from this new position _without_ the safe margin.
3. Do an overlap check at the unsafe fraction _with_ the safe margin and return the data.

(Note that the safe margin in this case refers to the `margin` parameter of the query, not the `margin` property of the shape itself.)

If you were to use something like `move_and_slide` this data would then get processed further, but I'm not familiar enough with its inner workings to go into details.

Again, I'm no expert on character controllers, so I can't really advise you on how to best fix yours, but I do believe some kind of changes need to be made to accommodate for these floating-point issues, and that this isn't an issue/bug with this extension per se.

> This also reveals another potential issue where some overlaps (both with shapecast overlap method and direct space state) appear to return some false negatives with box shape.

There have been issues in the past related to box shapes and disabling of shape margins, hence why I changed to a capsule shape in the above mentioned branch. It's a whole can of worms that I'm not sure is worth bringing up here, but basically if at all possible try to use a capsule shape, as it will yield much better collisions for something as sensitive as a character controller.

If Godot ever gets proper surface normals (see [this](https://github.com/godotengine/godot-proposals/issues/8324) proposal) as part of its contact data I will likely be removing the "Use Shape Margins" project setting, since rounded edge normals seems to be main motivation why people disable that setting.

**Comment by MarioBossReal** [comment] 2024-01-24 20:12
Thanks for this explanation. It makes sense that if the trace is already colliding, that it will miss the initial overlap and penetrate into the surface. I'm working on different solutions now to try and find the best one. The move_and_collide style solution does show some okay results, but it also results in some jitter when moving into corners just like the actual move_and_collide method, so I'll keep iterating until I find a good solution.

**Comment by MarioBossReal** [comment] 2024-01-24 20:16
`If Godot ever gets proper surface normals (see https://github.com/godotengine/godot-proposals/issues/8324 proposal) as part of its contact data I will likely be removing the "Use Shape Margins" project setting, since rounded edge normals seems to be main motivation why people disable that setting.`

I agree that Godot definitely needs to have a SurfaceNormal property when shapecasting, it would allow proper normal retreival whilst using a safe margin which would be quite beneficial. It's why im trying to avoid using margins wherever I can because I need precise normals on the edges of meshes.

**Comment by mihe** [comment] 2024-01-24 20:58
> but it also results in some jitter when moving into corners just like the actual move_and_collide method, so I'll keep iterating until I find a good solution.

When I first implemented `body_test_motion`/`move_and_collide` I ran into quite severe jitter in corners as well, but found that damping the iterative depenetration helped quite a bit. So basically not performing the full depenetration right away, but instead only depenetrate like 30% per iteration and instead do more iterations. Godot Physics does this as well. Might be worth a shot if you're not doing it already.

> I agree that Godot definitely needs to have a SurfaceNormal property when shapecasting, it would allow proper normal retreival whilst using a safe margin which would be quite beneficial. It's why im trying to avoid using margins wherever I can because I need precise normals on the edges of meshes.

I'll likely take a stab at implementing the proposal in a not too distant future. As mentioned in that proposal the data for Godot Physics is already there in the form of the shape's `get_support` method, and Jolt already provides a method for surface normals, so it should be fairly straight-forward. I just need to find the time.

**Comment by MarioBossReal** [comment] 2024-01-24 21:40
> When I first implemented `body_test_motion`/`move_and_collide` I ran into quite severe jitter in corners as well, but found that damping the iterative depenetration helped quite a bit. So basically not performing the full depenetration right away, but instead only depenetrate like 30% per iteration and instead do more iterations. Godot Physics does this as well. Might be worth a shot if you're not doing it already.

I've been working on it for a little while now and I think I've come to a solution that works quite well, I will post that snippet of the code here soon. I basically do a normal sweep and check the start and end overlaps and choose to either use the sweep or to do a depenetration phase and resweep, which seems to give the best results for each given situation.

> I'll likely take a stab at implementing the proposal in a not too distant future. As mentioned in that proposal the data for Godot Physics is already there in the form of the shape's `get_support` method, and Jolt already provides a method for surface normals, so it should be fairly straight-forward. I just need to find the time.

Sounds good! For my own purposes it's not the most urget thing, however it will definitely prove invaluable in the longrun.

**Comment by MarioBossReal** [comment] 2024-01-24 21:46
Here is the code for the character trace, it uses my sharptrace util if anyone checking in the future is confused, but the logic itself should be understandable.

```csharp
public CharacterTraceResult3D Trace()
{
    var result = new CharacterTraceResult3D();

    var origin = sweep.origin;
    var target = sweep.target;
    result.Origin = origin;

    var trace = sweep
         .From(origin)
         .To(target)
         .Margin(0)
         .Trace();

    // Check if we got stuck at any point without margins.
    var startSolid = CheckSolid(origin);
    var endSolid = CheckSolid(trace.SafeEndPoint);

    // Might have started solid, but should be unstuck
    if (!endSolid.IsColliding)
    {
        result.Point = trace.SafeEndPoint;
        result.AllSolid = false;
        result.Fraction = trace.SafeFraction;
        result.Travel = result.Origin.DistanceTo(result.Point);

        if (trace.IsColliding)
        {
            result.IsColliding = true;
            result.Normal = trace.Collisions[0].Normal;
        }

        return result;
    }

    // Sweep's initial overlap returned solid and was ignored.
    // May or may not have started solid.
    // This will result in clipping through geometry.
    if (endSolid.IsColliding)
    {
        // Try unsticking using margin and collision normal.
        int i;
        for (i = 0; i < 20; i++)
        {
            var unstuck = CheckSolid(result.Origin, 0.001f);
            if (!unstuck.IsColliding)
                break;

            var normal = unstuck.Collisions[0].Normal;
            result.Origin += normal * 0.005f;
        }

        // We couldn't unstick ourself.
        if (CheckSolid(result.Origin, 0.001f).IsColliding)
        {
            result.Point = origin;
            result.Normal = startSolid.Collisions[0].Normal;
            result.Collider = startSolid.Collisions[0].Collider;
            result.AllSolid = true;
            result.Fraction = 0f;
            result.Travel = 0f;
            result.IsColliding = true;
            return result;
        }

        // We managed to unstick our origin, now let's retrace our step.
        var trace2 = sweep
            .From(result.Origin)
            .To(target)
            .Margin(0)
            .Trace();

        result.Point = trace2.SafeEndPoint;
        result.AllSolid = false;
        result.Fraction = trace2.SafeFraction;
        result.Travel = origin.DistanceTo(result.Point);

        // Our new step might not have collided where our old step would have.
        // Use shape margin and unsafe fraction to get most accurate data.
        var endCheck = CheckSolid(trace2.UnsafeEndPoint, 0.001f);
        if (endCheck.IsColliding)
        {
            result.IsColliding = true;
            result.Normal = endCheck.Collisions[0].Normal;
        }
    }

    return result;
}
```
