### ISSUE TITLE
First-time torque-impulse doesn't apply correctly with certain global rotations and directions

### ISSUE THREAD

**Issue by nanodeath** [godot-jolt/godot-jolt#733] opened 2023-12-26 20:03 UTC
Okay, so I have this _insane_ bug...here are the (very approximate) steps to reproduce. It's hard to explain, so I've attached a sample project too.

1. Create a door-like object and add a HingeJoint3D to it.
2. Call `apply_torque_impulse` on the associated RigidBody3D.
3. Depending on the global rotation of the object and direction of rotation, the first time an impulse is applied, it'll be **much too small**. Specifically, if the object normally points along +X, and you rotate towards either +Z or -Z, and then apply a CW torque to it...the impulse is like 10 times too small.

## Sample Project

[GodotInsaneTorqueBug.zip](https://github.com/godot-jolt/godot-jolt/files/13773488/GodotInsaneTorqueBug.zip)

![image](https://github.com/godot-jolt/godot-jolt/assets/10625/09dddacb-7fdd-4efa-a614-1c2306230922)

https://github.com/godot-jolt/godot-jolt/assets/10625/231d57a3-ba7d-4613-9af7-a5390818e28c

I've attached a sample project. On the right side of the viewport are 4 doors in various orientations that open counter-clockwise if you left click it. On the left side of the viewport are 4 similar doors that open the other way -- clockwise. However, _some_ of the doors open with a significantly-reduced angular velocity, marked in red when the game starts (and annotated in the scene tree). Note you can close the doors by right-clicking them.

After the first interaction, things seem to work normally.

I've verified the behavior works as expected when using the default Godot physics engine.

---

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti with Max-Q Design (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

Godot Jolt 0.11.0

I created this project in Godot C# by accident, but all the scripts are .gd, so hopefully should work in either version of Godot.

**Comment by mihe** [comment] 2023-12-26 21:46
Thank you for reporting this, and for providing the minimal repro.

This behavior is indeed quite bizarre.

I'm not entirely sure what the cause of it is, but from just toying around with the values a bit I'm getting the sense that it has something to do with the "hack" I put in to allow for a more diverse set of angles for some of the joints, like `HingeJoint3D`.

This hack will essentially make it so that I always pass in symmetrical limits to Jolt, which in the case of this particular door hinge would be [60, 60] as opposed to something like [0, 120], and then I rotate the reference frame of the first body (`HingeStaticBody3D` in this case) to counteract this before passing it onto Jolt.

Here's what it looks like if I get rid of this hack:

https://github.com/godot-jolt/godot-jolt/assets/4884246/b935af64-a71b-45db-8523-5bf65a63ba02

I'll see if I can recreate this in Jolt's own `Samples` project tomorrow and then I'll report it upstream if I'm able to.

**Comment by mihe** [comment] 2023-12-26 22:03
As a temporary workaround, it looks like changing the joint limits from [0, 120] and [-120, 0] to [-0.1, 120] and [-120, 0.1] respectively gets rid of the strange behavior as well.

**Comment by jrouwe** [comment] 2023-12-30 17:38
Looking into this... (no need to create a repro, I can repro it like this)

**Comment by jrouwe** [comment] 2023-12-31 14:36
Should be fixed now in the latest version of Jolt. Thanks for reporting!

**Closed** 2024-01-02 14:45 UTC
Labels: bug, topic:runtime, severity:minor

**Comment by mihe** [comment] 2024-01-07 20:13
The fix for this is included in the newly released [0.12.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.12.0-stable).
